### ISSUE TITLE
support for Ampere GPU

### ISSUE THREAD

**Issue by easyrider14** [tkestack/gpu-manager#103]
Hi

I'm trying to use the gpu-manager on a Gigabyte G291-Z20 with 4 RTX 3090, but it does not seem to work
When setting the tencent.com/vcuda-core to 100 (or more), everything seems fine (I can run nvidia-smi with no problem for example)
But when setting it to less than 100, I can't even run nvidia-smi, and get the following error message
`F0628 09:26:08.086018      11 client.go:78] fail to get response from manager, error rpc error: code = Unknown desc = empty pids
/tmp/cuda-control/src/register.c:87 rpc client exit with 255
`

I have no problem using it on another rig with 2 GTX 1080 GPU

I have used gpu-manager image found on Docker Hub (thomassong/gpu-manager:1.1.5) and I have also built the image from source, with same result

Host is running Ubuntu 20.04.2 with nvidia drivers 460.73.01, Kubernetes 1.21.2

**Comment by mYmNeo** [comment]
Try to following #55 ?

**Comment by easyrider14** [comment]
thanks a lot, this solved my problem
