### ISSUE TITLE
`/etc/gpu-manager/vdriver/nvidia/lib64`中没有`libnvidia-ml.so.1`和`libcuda.so.1`

### ISSUE THREAD

**Issue by cailun01** [tkestack/gpu-manager#104]
我把gpu-manager运行起来之后，主机端的`/etc/gpu-manager/vdriver/nvidia/lib64`目录内中找不到`libnvidia-ml.so.1`和`libcuda.so.1`这两个动态库，从而导致生成的pod中运行nvidia-smi命令找不到`libnvidia-ml.so`。

我没有使用nvidia-docker，用的是docker原生的runc。
```json
{
  "log-level": "debug",
  "live-restore": true,
  "icc": false,
  "storage-driver": "overlay",
  "insecure-registries": ["qce-reg.nucpoc.com"],
  "live-restore": true,
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "512m",
    "max-file": "3"
  }
}
```
gpu-manager镜像版本1.1.4：
```
REPOSITORY                       TAG                  IMAGE ID            CREATED             SIZE
tkestack/gpu-manager             1.1.4                0a74a803da06        2 days ago          10.8 GB
```

开发者曾在其他问题中提到：`Please provides logs that contains Mirror %s to %s and Vcuda %s to %s`，请问这是什么意思？如何获得这些log？

**Comment by hzliangbin** [comment]
@cailun01 did you solve it?

**Comment by cailun01** [comment]
> @cailun01 did you solve it?

Unfortunately, I didn't.
