### ISSUE TITLE
[Question] Is memory isolation support yolo v2 or yolo v4?

### ISSUE THREAD

**Issue by peacealex63** [tkestack/gpu-manager#110]
Hi sir,
Thanks your great project sharing. When I set 
requests:
        tencent.com/vcuda-core: 100
        tencent.com/vcuda-memory: 20
      limits:
        tencent.com/vcuda-core: 100
        tencent.com/vcuda-memory: 20
But the GPU memory is still use almost 10G.
So is GPU manager support yolo v2 or v4 training?
Thanks.

**Comment by mYmNeo** [comment]
vcuda-core 100 mean use full card，no limitation enabled.
