### ISSUE TITLE
显存释放后，显示大小 > 显存实际大小

### ISSUE THREAD

**Issue by crushCoin** [tkestack/gpu-manager#114]
![image](https://user-images.githubusercontent.com/15995863/130923486-14dac05d-dca1-4e28-b3a7-fd500feddfd4.png)

**Comment by mYmNeo** [comment]
It's a log print error, it doesn't affect the allocation.

**Comment by crushCoin** [comment]
> It's a log print error, it doesn't affect the allocation.
好的，谢谢！
