### ISSUE TITLE
显存占用可能超过申请的大小，算力占用可能超过申请的算力

### ISSUE THREAD

**Issue by crushCoin** [tkestack/gpu-manager#115]
### 显存日志
![image](https://user-images.githubusercontent.com/15995863/130923998-702df3f3-fe79-4710-8eed-f2d52039e910.png)
### 算力日志
![image](https://user-images.githubusercontent.com/15995863/130924038-df57da5f-459e-4717-8505-a916930c27b6.png)

**Comment by mYmNeo** [comment]
For memory, nvidia sdk doesn't report context gpu memory, so the gpu memory may have a small diff from request.
For core, 0.5 means 50%, metric is percentage unit.

**Comment by crushCoin** [comment]
> For memory, nvidia sdk doesn't report context gpu memory, so the gpu memory may have a small diff from request.
> For core, 0.5 means 50%, metric is percentage unit.

docker daemon.json中去除 nvidia-container-runtime ，申请算力0.5，但是程序使用过程中有时可以超过0.6（即百分比 60）。

再请教2个问题：
1、cuda版本的兼容性，指的是宿主机cuda 驱动版本高于pod服务中镜像依赖的cuda版本就可以吗？
2、将gpu-manager的日志级别设置为6，为什么看不到类似如下日志呢？（这是从其他issue里面看到的）
/tmp/cuda-control/src/hijack_call.c:277 util: 85, up_limit: 24,  share: 929690, cur: 1310720
/tmp/cuda-control/src/hijack_call.c:277 util: 85, up_limit: 24,  share: 739175, cur: 1310720
/tmp/cuda-control/src/hijack_call.c:277 util: 85, up_limit: 24,  share: 548660, cur: 1096358

**Comment by mYmNeo** [comment]
> > For memory, nvidia sdk doesn't report context gpu memory, so the gpu memory may have a small diff from request.
> > For core, 0.5 means 50%, metric is percentage unit.
> 
> docker daemon.json中去除 nvidia-container-runtime ，申请算力0.5，但是程序使用过程中有时可以超过0.6（即百分比 60）。
> 
> ## 您好，再请教3个问题：
> 1、cuda版本的兼容性，指的是宿主机cuda 驱动版本高于pod服务中镜像依赖的cuda版本就可以吗？
> 2、将gpu-manager的日志级别设置为6，为什么看不到类似如下日志呢？（这是从其他issue里面看到的）
> /tmp/cuda-control/src/hijack_call.c:277 util: 85, up_limit: 24, share: 929690, cur: 1310720
> /tmp/cuda-control/src/hijack_call.c:277 util: 85, up_limit: 24, share: 739175, cur: 1310720
> /tmp/cuda-control/src/hijack_call.c:277 util: 85, up_limit: 24, share: 548660, cur: 1096358
> 3、从git上拉取代码，构建镜像，有如下错误提示，会影响gpu-admission gpu-manager的使用吗？
> Downloading packages:
> warning: /var/cache/yum/x86_64/7/base/packages/bzip2-1.0.6-13.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
> Public key for bzip2-1.0.6-13.el7.x86_64.rpm is not installed
> Public key for perl-Pod-Escapes-1.04-299.el7_9.noarch.rpm is not installed
> Total 2.7 MB/s | 16 MB 00:06
> Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
> Importing GPG key 0xF4A80EB5:
> Userid : "CentOS-7 Key (CentOS 7 Official Signing Key) [security@centos.org](mailto:security@centos.org)"
> Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
> Package : centos-release-7-9.2009.0.el7.centos.x86_64 (@CentOS)
> From : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

1. Yes
2. Read the FAQ link
3. Not affect
