### ISSUE TITLE
/tmp/cuda-control/src/loader.c can't find function cuEGLInit in libcuda.so.455.45.01

### ISSUE THREAD

**Issue by crushCoin** [tkestack/gpu-manager#119]
![2021-09-01_110410](https://user-images.githubusercontent.com/15995863/131629887-b46c646f-cd37-4235-af99-5079960a7bce.gif)
![企业微信截图_16304901239398](https://user-images.githubusercontent.com/15995863/131651701-9fa22937-7455-4db5-9c47-dbbf2f33fb55.png)
这个是由于pod镜像中 cuda版本过低  没有这些函数，只是提示，不影响使用是吗？

**Comment by mYmNeo** [comment]
It's compatible function, higher driver may not have these

**Comment by crushCoin** [comment]
好的，谢谢。
