### ISSUE TITLE
can't call gpu

### ISSUE THREAD

**Issue by SolarisYan** [tkestack/gpu-manager#12]
Hi, i have deploy the gpu-manager in my k8s, after some tests,  i find that if i use non root user in pod, i can't execute `nvidia-smi` command, only use root user can call it.

When i use non root user call nvidia-smi,  i use ps -ef to see what occur, i see:

```bash
gpu-client --addr /etc/vcuda/vcuda.sock --bus-id  --pod-uid f6d322b6-5480-11ea-a8b9-02f1556084e1 --cont-id 26b311b0df61a7008d52b3
```

hang there.

Does the manager only support root user to use it in pod?

**Comment by SolarisYan** [comment]
I use strace to debug it and find that
```bash
connect(4, {sa_family=AF_UNIX, sun_path="/etc/vcuda/vcuda.sock"}, 24) = -1 EACCES (Permission denied)
```

So how to solve this?

**Comment by SolarisYan** [comment]
got it

**Comment by linquanisaac** [comment]
@SolarisYan 
can you tell me how to fix it?

**Comment by raz-bn** [comment]
@SolarisYan @linquanisaac Hey can any of you share more information about the solution?

**Comment by mYmNeo** [comment]
You have to grant non-root user the permission of /etc/vcuda

**Comment by raz-bn** [comment]
> 
> 
> You have to grant non-root user the permission of /etc/vcuda

Thanks for the replay! 
Is there anyway to do so without setting:
```
      securityContext:
        privileged: true
```
In the YAML file?

**Comment by mYmNeo** [comment]
The `gpu-client` in the pod will read `/etc/vcuda/vcuda.sock` in container mount namespace. This file is generated by `gpu-manager` and mounted in the container. So you have to grant the rw permission in the `gpu-manager` namespace

**Comment by linquanisaac** [comment]
> @SolarisYan @linquanisaac Hey can any of you share more information about the solution?

I use root in container...

But I would try changing the sock permission after creating it.
