### ISSUE TITLE
Create pod that requests resource-CreateContainerConfigError

### ISSUE THREAD

**Issue by ruankee** [tkestack/gpu-manager#121]
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  26s                default-scheduler  Successfully assigned default/vcuda-test-7b4c8974bf-vqgm5 to node0
  Normal   Pulled     11s (x4 over 25s)  kubelet            Container image "ubuntu:18.04" already present on machine
  Warning  Failed     11s (x4 over 25s)  kubelet            Error: device plugin PreStartContainer rpc failed with err: rpc error: code = Unknown desc = PreStartContainer check failed, failed to read from checkpoint file due to json: cannot unmarshal object into Go struct field PodDevicesEntry.Data.PodDeviceEntries.DeviceIDs of type []string

**Comment by ruankee** [comment]
gpu-manager container uses image: tkestack/gpu-manager:v1.0.9

**Comment by mYmNeo** [comment]
You need upgrade gpu-manager to 1.1.x, 1.0.x not support higher k8s version

**Comment by ruankee** [comment]
> 
> 
> You need upgrade gpu-manager to 1.1.x, 1.0.x not support higher k8s version

when i use v1.1.2 ,gpu resource cannot be read
Capacity:
  cpu:                       6
  ephemeral-storage:         22443524Ki
  hugepages-1Gi:             0
  hugepages-2Mi:             0
  memory:                    8105592Ki
  nvidia.com/gpu:            2
  pods:                      110
  tencent.com/vcuda-core:    0
  tencent.com/vcuda-memory:  0
Allocatable:
  cpu:                       6
  ephemeral-storage:         21833060131
  hugepages-1Gi:             0
  hugepages-2Mi:             0
  memory:                    8105592Ki
  nvidia.com/gpu:            2
  pods:                      110
  tencent.com/vcuda-core:    0
  tencent.com/vcuda-memory:  0

**Comment by ruankee** [comment]
And gpu-manager daemonset pod status shows CRASHBACKLOOPOFF.When I check the pod log,it shows "unknown flag: --incluster-mode".

**Comment by ruankee** [comment]
I've found that the gpu-manager yaml file was outdated too.It include env"incluster-mode" and I delete it.The method upgrading gpu-manager actually works!Thanks!
