### ISSUE TITLE
Do you plan to fix the bug that the gpu-manager can't recognize pod correctly  as mentioned in the issue [#109] in near future?

### ISSUE THREAD

**Issue by shenchucheng** [tkestack/gpu-manager#124]
Hi:
        We tried to use gpu-manager to limit the gpu resource usage in the pod in our kubernetes cluster, and it worked very well when we set the  replicas value of the Deployment to 1, however, if the replicas set to 2, one of the pods failed to start and got error: "/tmp/cuda-control/src/loader.c:865 can't find library libcuda.so." This bug have been reported in the issue [#109], and it can resolve this problem temporarily to use statefulset, but it seems not a long-term solution, especially for production environments. And may I make so bold as to ask that wheather you have a plan to fix this bug in near further?  Thank you very much.

**Comment by mYmNeo** [comment]
We have done with a pre-released version to solve this problem, try image `thomassong/gpu-manager:master`, if no one report this issue again, we'll merge it into master and each release.
