### ISSUE TITLE
 fatal error: nvml.h: No such file or directory

### ISSUE THREAD

**Issue by a378603** [tkestack/gpu-manager#125]
Hi, 

When I use 'make', this error came.

In file included from /root/go/pkg/mod/github.com/tkestack/go-nvml@v0.0.0-20191217064248-7363e630a33e/binds.go:23:0:
/root/go/pkg/mod/github.com/tkestack/go-nvml@v0.0.0-20191217064248-7363e630a33e/nvml_dl.h:24:18: fatal error: nvml.h: No such file or directory
 #include "nvml.h"
                  ^
compilation terminated.

Can you or can someone tell me why I don't have this file?

Please

**Comment by yeqiugt** [comment]
@a378603 i met same err, can you give  me more information about how to sovle this?

**Comment by yeqiugt** [comment]
i have resovled, thanks a lot
