### ISSUE TITLE
CUDA Support  Version

### ISSUE THREAD

**Issue by alexk1028** [tkestack/gpu-manager#129]
首先感谢tke团队开源的这个组件，我们最近在尝试分割集群内的GPU实现显存隔离，中间也尝试了gpu-manager。我们没能在gpu-manager这个仓库中找到关于支持的CUDA版本（例如支持的CUDA版本列表/特定的CUDA），然后我们在vcuda-controller仓库的release中找到了一个支持CUDA10.2的信息。所以能在readme/其他地方中添加一下相关资料吗？谢谢

**Comment by mYmNeo** [comment]
We updated vcuda-controller README to make users know the restriction
