### ISSUE TITLE
Can't limit GPU utilization  

### ISSUE THREAD

**Issue by KarlCyan** [tkestack/gpu-manager#13]
## Describe the bug
GPU-Manager can limit GPU memory but can't limit GPU utilization

Pod yaml 
```
resources:
          requests:
            tencent.com/vcuda-core: 30
            tencent.com/vcuda-memory: 10
          limits:
            tencent.com/vcuda-core: 30
            tencent.com/vcuda-memory: 10
```
When i use tensorflow python code to test resource limit
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40       Driver Version: 430.40       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:65:00.0 Off |                  N/A |
| 41%   36C    P2    33W / 225W |   2379MiB /  7982MiB |      82%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2080    Off  | 00000000:B3:00.0 Off |                  N/A |
| 41%   32C    P8    18W / 225W |      0MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0    30846      C   python                                      2369MiB |
+-----------------------------------------------------------------------------+
```
## Environment
Kubernetes version : v1.13.2
TensorFlow version : 1.13.2-gpu

**Comment by knightXun** [comment]
do you install vcuda-controller?

**Comment by KarlCyan** [comment]
> do you install vcuda-controller?

Do I need to install vcuda-controller into a TensorFlow image or a gpu-manager?

**Comment by KarlCyan** [comment]
I tried to build the TensorFlow image with vcuda-controller (using build-image.sh), but the result is the same as now

**Comment by joyme123** [comment]
gpu-manager use elastic limit for computing resource, so if the gpu has free computer resource, gpu-manager will try to allocate more computing to container

**Comment by KarlCyan** [comment]
> gpu-manager use elastic limit for computing resource, so if the gpu has free computer resource, gpu-manager will try to allocate more computing resource to container

I made a test for this question :
### Description of YAMLs
```
[root@10 gpu]# cat test*.yaml | grep core
    tencent.com/vcuda-core-limit: '30'
        tencent.com/vcuda-core: 30
        tencent.com/vcuda-core: 30
    tencent.com/vcuda-core-limit: '20'
        tencent.com/vcuda-core: 20
        tencent.com/vcuda-core: 20
    tencent.com/vcuda-core-limit: '50'
        tencent.com/vcuda-core: 50
        tencent.com/vcuda-core: 50
```

### GPU-Manager Schedule Info
```
[root@10 log]# cat gpu-manager.INFO | grep "/dev/nvidia0 cores"
I0318 06:12:02.261929  224820 tree.go:483] /dev/nvidia0 cores 100->50
I0318 06:12:08.807669  224820 tree.go:483] /dev/nvidia0 cores 50->30
I0318 06:12:15.520206  224820 tree.go:483] /dev/nvidia0 cores 30->0
```

### vcuda Connection Info
```
I0318 06:16:35.140420  224820 manager.go:403] UID: c87e40d6-68de-11ea-9a69-005056bc1b59, cont: 68dd794ba24b47651445d06941551b2ea7abef8e59b0b6878d65b31667a08ad0 want to registration
I0318 06:16:35.140449  224820 manager.go:489] Write /etc/gpu-manager/vm/c87e40d6-68de-11ea-9a69-005056bc1b59/68dd794ba24b47651445d06941551b2ea7abef8e59b0b6878d65b31667a08ad0/pids.config
I0318 06:16:35.716302  224820 manager.go:403] UID: d065215f-68de-11ea-9a69-005056bc1b59, cont: 7635df1b4c9252866805fd90fbf6d4e11cb8a7e02ced0aee7bba0ad6d4b43e6d want to registration
I0318 06:16:35.716404  224820 manager.go:489] Write /etc/gpu-manager/vm/d065215f-68de-11ea-9a69-005056bc1b59/7635df1b4c9252866805fd90fbf6d4e11cb8a7e02ced0aee7bba0ad6d4b43e6d/pids.config
I0318 06:16:36.265576  224820 manager.go:403] UID: cc67df98-68de-11ea-9a69-005056bc1b59, cont: 88fa168728fc3833f4ba98229df5983e770ffde6250b21c6570aaa5601418cc1 want to registration
I0318 06:16:36.265673  224820 manager.go:489] Write /etc/gpu-manager/vm/cc67df98-68de-11ea-9a69-005056bc1b59/88fa168728fc3833f4ba98229df5983e770ffde6250b21c6570aaa5601418cc1/pids.config
```

### Result
I used the Tensor-Flow 1.13.2-gpu image to run the same test code
<img width="1439" alt="computed time" src="https://user-images.githubusercontent.com/26433127/76932070-02ce4380-6925-11ea-860d-8603e77c949c.png">

### Prometheus Result
<img width="1439" alt="promethus-limit" src="https://user-images.githubusercontent.com/26433127/76932308-90aa2e80-6925-11ea-82a5-d5e70758f97d.png">


They take the same time to complete under different resources, and compete for the computing resources of the GPU card.So I think my vcuda-core-limit has not worked

**Comment by mYmNeo** [comment]
What is your container runtime? `nvidia-docker` as container runtime will ruin the limitation function.

**Comment by KarlCyan** [comment]
> What is your container runtime? `nvidia-docker` as container runtime will ruin the limitation function.
> 
> PS: Please set LOG_LEVEL=5 environment to your Pod, then rerun your program. And filter out the log like `launch kernel`, paste it in your comment to help us to find the problem

When I was running the TensorFlow program, I found this information in the logs

```
I0325 02:15:24.847019  320864 manager.go:410] UID: e3be9533-5b06-4e4f-921d-d849e8733866, cont: 621cd0b70d4ee8e562c6d76826fe337b8946d78082a590321b995f92a65c1f93 want to registration
I0325 02:15:24.847074  320864 manager.go:496] Write /etc/gpu-manager/vm/e3be9533-5b06-4e4f-921d-d849e8733866/621cd0b70d4ee8e562c6d76826fe337b8946d78082a590321b995f92a65c1f93/pids.config
I0325 02:15:24.850671  320864 logs.go:79] transport: http2Server.HandleStreams failed to read frame: read unix /etc/gpu-manager/vm/e3be9533-5b06-4e4f-921d-d849e8733866/vcuda.sock->@: read: connection reset by peer
I0325 02:15:24.850760  320864 logs.go:79] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
I0325 02:15:26.081557  320864 manager.go:410] UID: 05079709-028e-46df-9c58-1e168a90fd6b, cont: 185fadc81742c96363333ce5e9ddd1a9e10c3247a2e958cd4d072d7fc2fff2f7 want to registration
I0325 02:15:26.081591  320864 manager.go:496] Write /etc/gpu-manager/vm/05079709-028e-46df-9c58-1e168a90fd6b/185fadc81742c96363333ce5e9ddd1a9e10c3247a2e958cd4d072d7fc2fff2f7/pids.config
I0325 02:15:26.085010  320864 logs.go:79] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
I0325 02:15:27.299614  320864 manager.go:410] UID: 69b10785-1a1b-48c2-9926-aa5a91ddabe6, cont: af2eaf2d2a4cc843e34ce2e65bf61674ac0b8214f119d4e5fefe58df2d24293b want to registration
I0325 02:15:27.299687  320864 manager.go:496] Write /etc/gpu-manager/vm/69b10785-1a1b-48c2-9926-aa5a91ddabe6/af2eaf2d2a4cc843e34ce2e65bf61674ac0b8214f119d4e5fefe58df2d24293b/pids.config
I0325 02:15:27.304507  320864 logs.go:79] transport: http2Server.HandleStreams failed to read frame: read unix /etc/gpu-manager/vm/69b10785-1a1b-48c2-9926-aa5a91ddabe6/vcuda.sock->@: read: connection reset by peer
I0325 02:15:27.304570  320864 logs.go:79] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

**Comment by mYmNeo** [comment]
> > What is your container runtime? `nvidia-docker` as container runtime will ruin the limitation function.
> > PS: Please set LOG_LEVEL=5 environment to your Pod, then rerun your program. And filter out the log like `launch kernel`, paste it in your comment to help us to find the problem
> 
> When I was running the TensorFlow program, I found this information in the logs
> 
> ```
> I0325 02:15:24.847019  320864 manager.go:410] UID: e3be9533-5b06-4e4f-921d-d849e8733866, cont: 621cd0b70d4ee8e562c6d76826fe337b8946d78082a590321b995f92a65c1f93 want to registration
> I0325 02:15:24.847074  320864 manager.go:496] Write /etc/gpu-manager/vm/e3be9533-5b06-4e4f-921d-d849e8733866/621cd0b70d4ee8e562c6d76826fe337b8946d78082a590321b995f92a65c1f93/pids.config
> I0325 02:15:24.850671  320864 logs.go:79] transport: http2Server.HandleStreams failed to read frame: read unix /etc/gpu-manager/vm/e3be9533-5b06-4e4f-921d-d849e8733866/vcuda.sock->@: read: connection reset by peer
> I0325 02:15:24.850760  320864 logs.go:79] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
> I0325 02:15:26.081557  320864 manager.go:410] UID: 05079709-028e-46df-9c58-1e168a90fd6b, cont: 185fadc81742c96363333ce5e9ddd1a9e10c3247a2e958cd4d072d7fc2fff2f7 want to registration
> I0325 02:15:26.081591  320864 manager.go:496] Write /etc/gpu-manager/vm/05079709-028e-46df-9c58-1e168a90fd6b/185fadc81742c96363333ce5e9ddd1a9e10c3247a2e958cd4d072d7fc2fff2f7/pids.config
> I0325 02:15:26.085010  320864 logs.go:79] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
> I0325 02:15:27.299614  320864 manager.go:410] UID: 69b10785-1a1b-48c2-9926-aa5a91ddabe6, cont: af2eaf2d2a4cc843e34ce2e65bf61674ac0b8214f119d4e5fefe58df2d24293b want to registration
> I0325 02:15:27.299687  320864 manager.go:496] Write /etc/gpu-manager/vm/69b10785-1a1b-48c2-9926-aa5a91ddabe6/af2eaf2d2a4cc843e34ce2e65bf61674ac0b8214f119d4e5fefe58df2d24293b/pids.config
> I0325 02:15:27.304507  320864 logs.go:79] transport: http2Server.HandleStreams failed to read frame: read unix /etc/gpu-manager/vm/69b10785-1a1b-48c2-9926-aa5a91ddabe6/vcuda.sock->@: read: connection reset by peer
> I0325 02:15:27.304570  320864 logs.go:79] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
> ```

The environment `LOG_LEVEL=5` is for `vcuda-controller` debugging.

**Comment by joyme123** [comment]
@KarlCyan @mYmNeo  I create 2 pods to see reproduce this problem. 

**pod1 with 20%core:**
```yaml
resources:
      requests:
        tencent.com/vcuda-core: 20
        tencent.com/vcuda-memory: 15
      limits:
        tencent.com/vcuda-core: 20
        tencent.com/vcuda-memory: 15
    env:
      - name: LOGGER_LEVEL
        value: "5"
```

**pod2 with 80% core:**
```yaml
    resources:
      requests:
        tencent.com/vcuda-core: 80
        tencent.com/vcuda-memory: 15
      limits:
        tencent.com/vcuda-core: 80
        tencent.com/vcuda-memory: 15
    env:
      - name: LOGGER_LEVEL
        value: "5"
```

the pod2 is faster than pod1，and this is the log about utilization: 

**pod1 with 20%core**
```
/tmp/cuda-control/src/hijack_call.c:276 util: 18, up_limit: 20,  share: 154742, cur: 141696
/tmp/cuda-control/src/hijack_call.c:276 util: 23, up_limit: 20,  share: 150510, cur: 150341
/tmp/cuda-control/src/hijack_call.c:276 util: 23, up_limit: 20,  share: 146278, cur: 146276
```

**pod2 with 80%core**
```
/tmp/cuda-control/src/hijack_call.c:276 util: 90, up_limit: 80,  share: 1398148, cur: 1507328
/tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1382067, cur: 1507328
/tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1365986, cur: 1507328
/tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1349905, cur: 1507328
/tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1333824, cur: 1507328
```

I think it succeed to limit GPU utilization. My question is that I just install gpu-manager, the deafult docker-runtime is nvidia-docker. But it worked well.

> What is your container runtime? nvidia-docker as container runtime will ruin the limitation function.

what is problem if the default runtime is nvidia-docker?

> do you install vcuda-controller?

what  "install vcuda-controller" means? I read  vcuda-controller's source code, it use `nanosleep()` the limit gpu utilization, that will work when program call CUDA api. gpu-manager copy "libcuda-control.so" and mount it for container to intercept  CUDA call. is these right?

so what else do i need to do after i install gpu-manager in kubernetes cluster?

**Comment by KarlCyan** [comment]
@joyme123 
I tried to adjust the LOG_LEVEL of gpu-manager to level 5, but I did not find logs similar to yours in the gpu-manager.INFO directory, like:
```
/tmp/cuda-control/src/hijack_call.c:276 util: 18, up_limit: 20,  share: 154742, cur: 141696
...
```

> what "install vcuda-controller" means? I read vcuda-controller's source code, it use nanosleep() the limit gpu utilization, that will work when program call CUDA api. gpu-manager copy "libcuda-control.so" and mount it for container to intercept CUDA call. is these right?

I have the same doubts about this problem, and it is still unclear how to install vcuda-controller. I confirmed that vcuda is installed in the pod of the gpu-manager.

>What is your container runtime? nvidia-docker as container runtime will ruin the limitation function.

I have tried both runtimes but got the same result: unable to limit GPU utilization

**Comment by joyme123** [comment]
@KarlCyan  You should set LOG_LEVEL to your pod which use GPU instead of gpu-manager.

**Comment by KarlCyan** [comment]
@mYmNeo 
###50% limit pod log: 
```
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507328
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507282
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507236
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507190
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507144
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507098
...
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1506638
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1506592
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1506546
```

### 20% limit pod log :
```
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507328
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507282
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507236
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507190
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507144
...
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1498036
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1497990
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1497944
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1497898
```

**Comment by KarlCyan** [comment]
@mYmNeo 

These two pods are running at the same time.

### 50% limit pod log:
```
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507328
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507282
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507236
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507190
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507144
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507098
...
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1506638
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1506592
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1506546
```

### 20% limit pod log :
```
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507328
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507282
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507236
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507190
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507144
...
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1498036
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1497990
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1497944
/tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1497898
```

**Comment by mYmNeo** [comment]
> @KarlCyan @mYmNeo I create 2 pods to reproduce this problem.
> 
> **pod1 with 20%core:**
> 
> ```yaml
> resources:
>       requests:
>         tencent.com/vcuda-core: 20
>         tencent.com/vcuda-memory: 15
>       limits:
>         tencent.com/vcuda-core: 20
>         tencent.com/vcuda-memory: 15
>     env:
>       - name: LOGGER_LEVEL
>         value: "5"
> ```
> 
> **pod2 with 80% core:**
> 
> ```yaml
>     resources:
>       requests:
>         tencent.com/vcuda-core: 80
>         tencent.com/vcuda-memory: 15
>       limits:
>         tencent.com/vcuda-core: 80
>         tencent.com/vcuda-memory: 15
>     env:
>       - name: LOGGER_LEVEL
>         value: "5"
> ```
> 
> the pod2 is faster than pod1，and this is the log about utilization:
> 
> **pod1 with 20%core**
> 
> ```
> /tmp/cuda-control/src/hijack_call.c:276 util: 18, up_limit: 20,  share: 154742, cur: 141696
> /tmp/cuda-control/src/hijack_call.c:276 util: 23, up_limit: 20,  share: 150510, cur: 150341
> /tmp/cuda-control/src/hijack_call.c:276 util: 23, up_limit: 20,  share: 146278, cur: 146276
> ```
> 
> **pod2 with 80%core**
> 
> ```
> /tmp/cuda-control/src/hijack_call.c:276 util: 90, up_limit: 80,  share: 1398148, cur: 1507328
> /tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1382067, cur: 1507328
> /tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1365986, cur: 1507328
> /tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1349905, cur: 1507328
> /tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1333824, cur: 1507328
> ```
> 
> I think it succeed to limit GPU utilization. My question is that I just install gpu-manager, the deafult docker-runtime is nvidia-docker. But it worked well.
> 
> > What is your container runtime? nvidia-docker as container runtime will ruin the limitation function.
> 
> what is problem if the default runtime is nvidia-docker?
> 
> > do you install vcuda-controller?
> 
> what "install vcuda-controller" means? I read vcuda-controller's source code, it use `nanosleep()` the limit gpu utilization, that will work when program call CUDA api. gpu-manager copy "libcuda-control.so" and mount it for container to intercept CUDA call. is these right?
> 
> so what else do i need to do after i install gpu-manager in kubernetes cluster?

nvidia-docker runtime will read some environment variables started with NV_ of your container, then hook and modify the running environment of your container. So we suggest not use `nvidia-docker` as the default container runtime.

**Comment by mYmNeo** [comment]
> @mYmNeo
> 
> These two pods are running at the same time.
> 
> ### 50% limit pod log:
> ```
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507328
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507282
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507236
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507190
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507144
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507098
> ...
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1506638
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1506592
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1506546
> ```
> 
> ### 20% limit pod log :
> ```
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507328
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507282
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507236
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507190
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1507144
> ...
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1498036
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1497990
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1497944
> /tmp/cuda-control/src/hijack_call.c:167 launch kernel 46, curr core: 1497898
> ```

Are these all the relative logs? If so, the controller maybe not handle fewer requests of calculation. Because of the closed source of `NVIDIA` driver, we can only limit the requests of calculation but can't control the context switch in the kernel. So if your application just emits few requests but each of them is huge computation, we may not cover this. The best practice is to run a real training program like `Alexnet` or others with continuous computation.

**Comment by raz-bn** [comment]
> 
> 
> > @KarlCyan @mYmNeo I create 2 pods to reproduce this problem.
> > **pod1 with 20%core:**
> > ```yaml
> > resources:
> >       requests:
> >         tencent.com/vcuda-core: 20
> >         tencent.com/vcuda-memory: 15
> >       limits:
> >         tencent.com/vcuda-core: 20
> >         tencent.com/vcuda-memory: 15
> >     env:
> >       - name: LOGGER_LEVEL
> >         value: "5"
> > ```
> > 
> > 
> > **pod2 with 80% core:**
> > ```yaml
> >     resources:
> >       requests:
> >         tencent.com/vcuda-core: 80
> >         tencent.com/vcuda-memory: 15
> >       limits:
> >         tencent.com/vcuda-core: 80
> >         tencent.com/vcuda-memory: 15
> >     env:
> >       - name: LOGGER_LEVEL
> >         value: "5"
> > ```
> > 
> > 
> > the pod2 is faster than pod1，and this is the log about utilization:
> > **pod1 with 20%core**
> > ```
> > /tmp/cuda-control/src/hijack_call.c:276 util: 18, up_limit: 20,  share: 154742, cur: 141696
> > /tmp/cuda-control/src/hijack_call.c:276 util: 23, up_limit: 20,  share: 150510, cur: 150341
> > /tmp/cuda-control/src/hijack_call.c:276 util: 23, up_limit: 20,  share: 146278, cur: 146276
> > ```
> > 
> > 
> > **pod2 with 80%core**
> > ```
> > /tmp/cuda-control/src/hijack_call.c:276 util: 90, up_limit: 80,  share: 1398148, cur: 1507328
> > /tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1382067, cur: 1507328
> > /tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1365986, cur: 1507328
> > /tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1349905, cur: 1507328
> > /tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1333824, cur: 1507328
> > ```
> > 
> > 
> > I think it succeed to limit GPU utilization. My question is that I just install gpu-manager, the deafult docker-runtime is nvidia-docker. But it worked well.
> > > What is your container runtime? nvidia-docker as container runtime will ruin the limitation function.
> > 
> > 
> > what is problem if the default runtime is nvidia-docker?
> > > do you install vcuda-controller?
> > 
> > 
> > what "install vcuda-controller" means? I read vcuda-controller's source code, it use `nanosleep()` the limit gpu utilization, that will work when program call CUDA api. gpu-manager copy "libcuda-control.so" and mount it for container to intercept CUDA call. is these right?
> > so what else do i need to do after i install gpu-manager in kubernetes cluster?
> 
> nvidia-docker runtime will read some environment variables started with NV_ of your container, then hook and modify the running environment of your container. So we suggest not use `nvidia-docker` as the default container runtime.

What other default container runtime do you suggest? 
Will cri-o work?

**Comment by mYmNeo** [comment]
> > > @KarlCyan @mYmNeo I create 2 pods to reproduce this problem.
> > > **pod1 with 20%core:**
> > > ```yaml
> > > resources:
> > >       requests:
> > >         tencent.com/vcuda-core: 20
> > >         tencent.com/vcuda-memory: 15
> > >       limits:
> > >         tencent.com/vcuda-core: 20
> > >         tencent.com/vcuda-memory: 15
> > >     env:
> > >       - name: LOGGER_LEVEL
> > >         value: "5"
> > > ```
> > > 
> > > 
> > > **pod2 with 80% core:**
> > > ```yaml
> > >     resources:
> > >       requests:
> > >         tencent.com/vcuda-core: 80
> > >         tencent.com/vcuda-memory: 15
> > >       limits:
> > >         tencent.com/vcuda-core: 80
> > >         tencent.com/vcuda-memory: 15
> > >     env:
> > >       - name: LOGGER_LEVEL
> > >         value: "5"
> > > ```
> > > 
> > > 
> > > the pod2 is faster than pod1，and this is the log about utilization:
> > > **pod1 with 20%core**
> > > ```
> > > /tmp/cuda-control/src/hijack_call.c:276 util: 18, up_limit: 20,  share: 154742, cur: 141696
> > > /tmp/cuda-control/src/hijack_call.c:276 util: 23, up_limit: 20,  share: 150510, cur: 150341
> > > /tmp/cuda-control/src/hijack_call.c:276 util: 23, up_limit: 20,  share: 146278, cur: 146276
> > > ```
> > > 
> > > 
> > > **pod2 with 80%core**
> > > ```
> > > /tmp/cuda-control/src/hijack_call.c:276 util: 90, up_limit: 80,  share: 1398148, cur: 1507328
> > > /tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1382067, cur: 1507328
> > > /tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1365986, cur: 1507328
> > > /tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1349905, cur: 1507328
> > > /tmp/cuda-control/src/hijack_call.c:276 util: 99, up_limit: 80,  share: 1333824, cur: 1507328
> > > ```
> > > 
> > > 
> > > I think it succeed to limit GPU utilization. My question is that I just install gpu-manager, the deafult docker-runtime is nvidia-docker. But it worked well.
> > > > What is your container runtime? nvidia-docker as container runtime will ruin the limitation function.
> > > 
> > > 
> > > what is problem if the default runtime is nvidia-docker?
> > > > do you install vcuda-controller?
> > > 
> > > 
> > > what "install vcuda-controller" means? I read vcuda-controller's source code, it use `nanosleep()` the limit gpu utilization, that will work when program call CUDA api. gpu-manager copy "libcuda-control.so" and mount it for container to intercept CUDA call. is these right?
> > > so what else do i need to do after i install gpu-manager in kubernetes cluster?
> > 
> > 
> > nvidia-docker runtime will read some environment variables started with NV_ of your container, then hook and modify the running environment of your container. So we suggest not use `nvidia-docker` as the default container runtime.
> 
> What other default container runtime do you suggest?
> Will cri-o work?

Currently only docker runtime is tested. If you expect another runtime like `cri-o`, please open another issue and address container runtime that you want to support.
