### ISSUE TITLE
GeForce RTX 3090 GPU Pod created ，output error

### ISSUE THREAD

**Issue by dwbxm** [tkestack/gpu-manager#138]
### 1、problem
I1227 15:49:36.935159   23378 util.go:265] No assigned flag for pod gpu-test in namespace default
I1227 15:49:36.935210   23378 allocator.go:1145] candidate pod gpu-test in ns default with timestamp 1640591376000000000 is found.
I1227 15:49:36.935254   23378 allocator.go:723] Found candidate Pod e30f0dbe-8a7f-4135-b223-489b0a9f2caf(gpu-test) with device count 100
I1227 15:49:36.935277   23378 util.go:227] Determine if the pod gpu-test needs GPU resource
I1227 15:49:36.935319   23378 util.go:240] No predicate time for pod gpu-test in namespace default
I1227 15:49:36.958928   23378 tree.go:119] Update device information
I1227 15:49:36.965141   23378 tree.go:135] node 0, pid: [], memory: 0, utilization: 0, pendingReset: false
I1227 15:49:36.965969   23378 allocator.go:375] Tree graph: ROOT:1
|---GPU0 (pids: [], usedMemory: 0, totalMemory: 25447170048, allocatableCores: 100, allocatableMemory: 25447170048)
I1227 15:49:36.965999   23378 allocator.go:386] Try allocate for e30f0dbe-8a7f-4135-b223-489b0a9f2caf(gpu-test), vcore 100, vmemory 10737418240
I1227 15:49:36.966024   23378 node.go:107] Pick up 0 mask 1
I1227 15:49:36.966035   23378 fragment.go:73] Pick up 0 mask 1
I1227 15:49:36.966054   23378 allocator.go:482] Allocate /dev/nvidia0 for e30f0dbe-8a7f-4135-b223-489b0a9f2caf(gpu-test), Meta (0:0)
I1227 15:49:36.966071   23378 tree.go:491] Occupy /dev/nvidia0 with 100 10737418240, mask 1
I1227 15:49:36.966082   23378 tree.go:518] Occupy /dev/nvidia0 parent 1
I1227 15:49:36.966091   23378 tree.go:496] /dev/nvidia0 cores 100->0
I1227 15:49:36.966115   23378 tree.go:497] /dev/nvidia0 memory 25447170048->0
I1227 15:49:36.970721   23378 manager.go:378] process e30f0dbe-8a7f-4135-b223-489b0a9f2caf
I1227 15:49:36.970921   23378 manager.go:616] vDevice registering on /etc/gpu-manager/vm/e30f0dbe-8a7f-4135-b223-489b0a9f2caf/vcuda.sock
I1227 15:49:36.970990   23378 manager.go:636] vDevice server started on /etc/gpu-manager/vm/e30f0dbe-8a7f-4135-b223-489b0a9f2caf/vcuda.sock
I1227 15:49:36.970999   23378 manager.go:371] Start vDevice server for /etc/gpu-manager/vm/e30f0dbe-8a7f-4135-b223-489b0a9f2caf, srv 2
I1227 15:49:37.937371   23378 vmemory.go:107] PreStartContainer request for vmemory
I1227 15:49:37.938256   23378 vcore.go:103] PreStartContainer request for vcore
I1227 15:49:37.938384   23378 util.go:130] Try v2 checkpoint data format
I1227 15:49:37.939071   23378 allocator.go:806] PreStartContainer check failed, failed to read from checkpoint file due to json: cannot unmarshal object into Go struct field PodDevicesEntry.Data.PodDeviceEntries.DeviceIDs of type []string
I1227 15:49:39.741197   23378 vcore.go:103] PreStartContainer request for vcore
I1227 15:49:39.741293   23378 util.go:130] Try v2 checkpoint data format
I1227 15:49:39.741761   23378 allocator.go:806] PreStartContainer check failed, failed to read from checkpoint file due to json: cannot unmarshal object into Go struct field PodDevicesEntry.Data.PodDeviceEntries.DeviceIDs of type []string

### 2、environment
Linux 10.140.6.57 5.4.104-1.el7.elrepo.x86_64  SMP Mon Mar 8 16:59:45 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
GeForce RTX 3090
Driver Version: 460.67       CUDA Version: 11.2
gpu-manager: 1.1.0
kubernetes: v1.20.11

**What does result in the problem? Kubernetes version can not match the gpu-manager version? Thank you.**

@mYmNeo

**Comment by mYmNeo** [comment]
You need use gpu-manager higher than 1.1

**Comment by dwbxm** [comment]
> You need use gpu-manager higher than 1.1

Can I degrade the kubernetes version to 1.18.3? I will try.

Thank you.
