### ISSUE TITLE
请问去掉manager和scheduler选择的节点是否一致的校验有没有风险？

### ISSUE THREAD

**Issue by jdhxf** [tkestack/gpu-manager#142]
https://github.com/tkestack/gpu-manager/blob/c961e77c3e65ef68299d0ba8ccb945b063896a03/pkg/services/allocator/nvidia/allocator.go#L462

自测了一下，暂时没发现问题。
为什么去掉？主要是因为本来的scheduler的预测很难和manager保持一致，现在想以scheduler为准。

谢谢回答~

**Comment by WulixuanS** [comment]
+1，滚动并发度高的情况下，经常出现选卡不一致，现在想使用manager选的卡为准，这样有问题吗

**Comment by jdhxf** [comment]
@mYmNeo 辛苦帮忙确认一下，感谢~~

**Comment by mYmNeo** [comment]
Only metrics may have confusing card report
