### ISSUE TITLE
should gpu-manager deal with LD_LIBRARY_PATH more carefully?

### ISSUE THREAD

**Issue by joyme123** [tkestack/gpu-manager#16]
```go
	// LD_LIBRARY_PATH
	ctntResp.Envs["LD_LIBRARY_PATH"] = "/usr/local/nvidia/lib64"
	for _, env := range container.Env {
		if env.Name == "compat32" && strings.ToLower(env.Value) == "true" {
			ctntResp.Envs["LD_LIBRARY_PATH"] = "/usr/local/nvidia/lib"
		}
	}
```
this will cause some container with LD_LIBRARY_PATH does't work correctly. 
For example:

I use tensorflow-serving image to serve model from HDFS. So I need to use LD_LIBRARY_PATH for `libhdfs.so`. my dockerfile likes this:

```
FROM tensorflow/serving:1.14.0-gpu
...

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
ENV HADOOP_HDFS_HOME /root/hadoop
ENV LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${JAVA_HOME}/jre/lib/amd64/server

...
```
Because of this, I have to rebuild these image, change it to:

```
RUN echo '/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server' > /etc/ld.so.conf.d/hdfs.conf
```
So i think if gpu-manager should deal with `LD_LIBRARY_PATH` more carefully. One possible way is that only overwrite part of `LD_LIBRARY_PATH`  value: the path contains `cuda` or `nvidia`.

**Comment by mYmNeo** [comment]
> ```go
> 	// LD_LIBRARY_PATH
> 	ctntResp.Envs["LD_LIBRARY_PATH"] = "/usr/local/nvidia/lib64"
> 	for _, env := range container.Env {
> 		if env.Name == "compat32" && strings.ToLower(env.Value) == "true" {
> 			ctntResp.Envs["LD_LIBRARY_PATH"] = "/usr/local/nvidia/lib"
> 		}
> 	}
> ```
> 
> this will cause some container with LD_LIBRARY_PATH does't work correctly.
> For example:
> 
> I use tensorflow-serving image to serve model from HDFS. So I need to use LD_LIBRARY_PATH for `libhdfs.so`. my dockerfile likes this:
> 
> ```
> FROM tensorflow/serving:1.14.0-gpu
> ...
> 
> ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
> ENV HADOOP_HDFS_HOME /root/hadoop
> ENV LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${JAVA_HOME}/jre/lib/amd64/server
> 
> ...
> ```
> 
> Because of this, I have to rebuild these image, change it to:
> 
> ```
> RUN echo '/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server' > /etc/ld.so.conf.d/hdfs.conf
> ```
> 
> So i think if gpu-manager should deal with `LD_LIBRARY_PATH` more carefully. One possible way is that only overwrite part of `LD_LIBRARY_PATH` value: the path contains `cuda` or `nvidia`.

It is not possible to read environment variables without modifying the docker code which it's what `nvidia-docker` does. So the best practice is to set environment variables in bash script.
