### ISSUE TITLE
a question about Allocate for a container?

### ISSUE THREAD

**Issue by joyme123** [tkestack/gpu-manager#17]
[pkg/services/allocator/nvidia/allocator.go#L781](https://github.com/tkestack/gpu-manager/blob/1f3c5e3a33bfc201f4d56b22f7d7cd196247b5db/pkg/services/allocator/nvidia/allocator.go#L781)

```go
pods, err := getCandidatePods(ta.k8sClient, ta.config.Hostname)
if err != nil {
	msg := fmt.Sprintf("Failed to find candidate pods due to %v", err)
	glog.Infof(msg)
	return nil, fmt.Errorf(msg)
}

for _, pod := range pods {
	if found {
		break
	}
	for i, c := range pod.Spec.Containers {
		if !utils.IsGPURequiredContainer(&c) {
			continue
		}
		podCache := ta.allocatedPod.GetCache(string(pod.UID))
		if podCache != nil {
			if _, ok := podCache[c.Name]; ok {
				glog.Infof("container %s of pod %s has been allocate, continue to next", c.Name, pod.UID)
				continue
			}
		}
		// 这里只根据容器的 vcore 请求量对比，能保证当前的 pod 是 kubelet Allocate 的容器所属的Pod吗？
		if utils.GetGPUResourceOfContainer(&pod.Spec.Containers[i], types.VCoreAnnotation) == reqCount {
			glog.Infof("Found candidate Pod %s(%s) with device count %d", pod.UID, c.Name, reqCount)
			candidatePod = pod
			candidateContainer = &pod.Spec.Containers[i]
			found = true
			break
		}
	}
}
```

when kubelet call `Allocate` for a container，it sorted the candidate pods by predicatedTime or createTime，and find the container which vcore equals with request count. But if there are two pods: A and B. A is created before B. Their vcore request is same, but vmemory is different. If pod B bind node before A. the candidateContainer will be wrong. 

> 整个调度流水线只有在 Scheduler Thread 阶段是串行的一个 Pod 一个 Pod 的进行调度，在 Wait 和 Bind 阶段 Pod 都是异步并行执行。

reference article: [从零开始入门 K8s：调度器的调度流程和算法介绍](https://www.infoq.cn/article/or7CRphTDlX1IVhsFNgk)

Or does A always bind node before B?

**Comment by mYmNeo** [comment]
> [pkg/services/allocator/nvidia/allocator.go#L781](https://github.com/tkestack/gpu-manager/blob/1f3c5e3a33bfc201f4d56b22f7d7cd196247b5db/pkg/services/allocator/nvidia/allocator.go#L781)
> 
> ```go
> pods, err := getCandidatePods(ta.k8sClient, ta.config.Hostname)
> if err != nil {
> 	msg := fmt.Sprintf("Failed to find candidate pods due to %v", err)
> 	glog.Infof(msg)
> 	return nil, fmt.Errorf(msg)
> }
> 
> for _, pod := range pods {
> 	if found {
> 		break
> 	}
> 	for i, c := range pod.Spec.Containers {
> 		if !utils.IsGPURequiredContainer(&c) {
> 			continue
> 		}
> 		podCache := ta.allocatedPod.GetCache(string(pod.UID))
> 		if podCache != nil {
> 			if _, ok := podCache[c.Name]; ok {
> 				glog.Infof("container %s of pod %s has been allocate, continue to next", c.Name, pod.UID)
> 				continue
> 			}
> 		}
> 		// 这里只根据容器的 vcore 请求量对比，能保证当前的 pod 是 kubelet Allocate 的容器所属的Pod吗？
> 		if utils.GetGPUResourceOfContainer(&pod.Spec.Containers[i], types.VCoreAnnotation) == reqCount {
> 			glog.Infof("Found candidate Pod %s(%s) with device count %d", pod.UID, c.Name, reqCount)
> 			candidatePod = pod
> 			candidateContainer = &pod.Spec.Containers[i]
> 			found = true
> 			break
> 		}
> 	}
> }
> ```
> 
> when kubelet call `Allocate` for a container，it sorted the candidate pods by predicatedTime or createTime，and find the container which vcore equals with request count. But if there are two pods: A and B. A is created before B. Their vcore request is same, but vmemory is different. If pod B bind node before A. the candidateContainer will be wrong.
> 
> > 整个调度流水线只有在 Scheduler Thread 阶段是串行的一个 Pod 一个 Pod 的进行调度，在 Wait 和 Bind 阶段 Pod 都是异步并行执行。
> 
> reference article: [从零开始入门 K8s：调度器的调度流程和算法介绍](https://www.infoq.cn/article/or7CRphTDlX1IVhsFNgk)
> 
> Or does A always bind node before B?

It can't be guaranteed that all Pods are allocated in the order of `createTime`. So sometimes the manager will report a UnexpectedAdmissionError.

**Comment by joyme123** [comment]
@mYmNeo Thanks for your reply.
