### ISSUE TITLE
make img failed

### ISSUE THREAD

**Issue by yeqiugt** [tkestack/gpu-manager#174]
When I use  `make img` to build image, a mistake appeared:

```
Step 15/34 : WORKDIR /root/rpmbuild/SPECS
 ---> Running in 6f049948bd19
Removing intermediate container 6f049948bd19
 ---> 065c57d8a999
Step 16/34 : RUN rpmbuild -bb --quiet   --define 'version '${version}''   --define 'commit '${commit}''   gpu-manager.spec
 ---> Running in c7a43da284d5
/usr/bin/tar: Removing leading `/' from member names
/var/tmp/rpm-tmp.IoDf4V: line 35: cd: gpu-manager-1.1.4: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.IoDf4V (%prep)
    Bad exit status from /var/tmp/rpm-tmp.IoDf4V (%prep)
The command '/bin/sh -c rpmbuild -bb --quiet   --define 'version '${version}''   --define 'commit '${commit}''   gpu-manager.spec' returned a non-zero code: 1

```

I use the lateest code,  docker version 20.10.17, go version go1.17.7 linux/amd64, centos 7.
Is there maintainer or anyone can help me?

**Comment by mingkai-yang** [comment]
请问 build中的Dockerfile中的 基础镜像 nvidia/cuda:10.1-devel-centos7 怎样才能获取到

**Comment by yeqiugt** [comment]
去dockerhub nvidia的仓库，nvidia会定期清理掉太旧的镜像，10.1可能不存在，可以试试更新的版本

**Comment by yeqiugt** [comment]
> 请问 build中的Dockerfile中的 基础镜像 nvidia/cuda:10.1-devel-centos7 怎样才能获取到


去dockerhub nvidia的仓库，nvidia会定期清理掉太旧的镜像，10.1可能不存在，可以试试更新的版本

**Comment by mingkai-yang** [comment]
> > 请问 build中的Dockerfile中的 基础镜像 nvidia/cuda:10.1-devel-centos7 怎样才能获取到
> 
> 去dockerhub nvidia的仓库，nvidia会定期清理掉太旧的镜像，10.1可能不存在，可以试试更新的版本

我确实去nvidia仓库找了，已经没有10.1这个了
请问楼主后续有投入使用这种虚拟化方式吗？
我在集群同一批机器上使用 [单卡共享]、[单卡独占]、[多卡独占] 混合任务时，某些机器上vcua core满足，pod调度成功，但创建失败，gpu-manager 日志在一直提示 no free node，我猜测可能是机器上混合使用不同模式导致的，是不是需要不同模式任务 要做隔离呢

**Comment by yeqiugt** [comment]
> > > 请问 build中的Dockerfile中的 基础镜像 nvidia/cuda:10.1-devel-centos7 怎样才能获取到
> > 
> > 
> > 去dockerhub nvidia的仓库，nvidia会定期清理掉太旧的镜像，10.1可能不存在，可以试试更新的版本
> 
> 我确实去nvidia仓库找了，已经没有10.1这个了 请问楼主后续有投入使用这种虚拟化方式吗？ 我在集群同一批机器上使用 [单卡共享]、[单卡独占]、[多卡独占] 混合任务时，某些机器上vcua core满足，pod调度成功，但创建失败，gpu-manager 日志在一直提示 no free node，我猜测可能是机器上混合使用不同模式导致的，是不是需要不同模式任务 要做隔离呢

后续深入了解过k8s层面的东西，再底层就不了解了；gpu-manager报错需要更详细的信息。

**Comment by mingkai-yang** [comment]
> > > > 请问 build中的Dockerfile中的 基础镜像 nvidia/cuda:10.1-devel-centos7 怎样才能获取到
> > > 
> > > 
> > > 去dockerhub nvidia的仓库，nvidia会定期清理掉太旧的镜像，10.1可能不存在，可以试试更新的版本
> > 
> > 
> > 我确实去nvidia仓库找了，已经没有10.1这个了 请问楼主后续有投入使用这种虚拟化方式吗？ 我在集群同一批机器上使用 [单卡共享]、[单卡独占]、[多卡独占] 混合任务时，某些机器上vcua core满足，pod调度成功，但创建失败，gpu-manager 日志在一直提示 no free node，我猜测可能是机器上混合使用不同模式导致的，是不是需要不同模式任务 要做隔离呢
> 
> 后续深入了解过k8s层面的东西，再底层就不了解了；gpu-manager报错需要更详细的信息。

好的 感谢
