### ISSUE TITLE
Can not make different vcuda-core limits and requests

### ISSUE THREAD

**Issue by scxu** [tkestack/gpu-manager#20]
The article "GaiaGPU: Sharing GPUs in Container Clouds" shows a very great work in nvidia gpu virtualization. And here is a question about the part "Elastic Resource allocation". 

In this part an experiment shows a container with 0.3 GPU can use more resources if the another part of gpu is idle, but in the pod configuration I can't make the `requests.tencent.com/vcuda-core` and `limits.tencent.com/vcuda-core` different. For example if I define a pod with `limits.tencent.com/vcuda-core: 90` and `requests.tencent.com/vcuda-core: 30` it will show error like this:

> The Pod "vgpu-test-1" is invalid: spec.containers[0].resources.requests: Invalid value: "30": must be equal to tencent.com/vcuda-core limit

**Comment by Servon-Lee** [comment]
@scxu 
Hi there, do you figure out the problem? And how do you implement the elastic resource allocation?
