### ISSUE TITLE
cni@v0.6.0 下载错误

### ISSUE THREAD

**Issue by iotctech** [tkestack/gpu-manager#22]
执行make的时候，多次尝试下载cni失败。

`hack/build.sh manager client
go: downloading google.golang.org/grpc v1.25.1
go: downloading github.com/gogo/protobuf v1.1.1
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.12.1
go: downloading golang.org/x/net v0.0.0-20191109021931-daa7c04131f5
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/prometheus/client_golang v1.2.1
go: downloading golang.org/x/sys v0.0.0-20191010194322-b09406accb47
go: downloading github.com/docker/go-connections v0.3.0
go: downloading github.com/kubernetes/kubernetes/staging/src/k8s.io/apimachinery v0.0.0-20190816231410-2d3c76f9091b
go: downloading github.com/kubernetes/kubernetes/staging/src/k8s.io/client-go v0.0.0-20190816231410-2d3c76f9091b
go: downloading github.com/docker/docker v0.7.3-0.20190327010347-be7ac8be2ae0
go: downloading github.com/tkestack/go-nvml v0.0.0-20191217064248-7363e630a33e
go: downloading github.com/kubernetes/kubernetes/staging/src/k8s.io/api v0.0.0-20190816231410-2d3c76f9091b
go: downloading github.com/kubernetes/kubernetes/staging/src/k8s.io/cri-api v0.0.0-20190816231410-2d3c76f9091b
go: downloading github.com/kubernetes/kubernetes/staging/src/k8s.io/apiserver v0.0.0-20190816231410-2d3c76f9091b
go: downloading github.com/opencontainers/runc v0.0.0-20181113202123-f000fe11ece1
go: downloading github.com/docker/distribution v0.0.0-20170726174610-edc3ab29cdff
go: downloading github.com/spf13/afero v0.0.0-20160816080757-b28a7effac97
go: downloading google.golang.org/genproto v0.0.0-20191108220845-16a3f7862a1a
go: downloading github.com/google/cadvisor v0.33.2-0.20190411163913-9db8c7dee20a
go: downloading github.com/kubernetes/kubernetes/staging/src/k8s.io/apiextensions-apiserver v0.0.0-20190816231410-2d3c76f9091b
go: downloading github.com/containernetworking/cni v0.6.0
go: downloading github.com/emicklei/go-restful v0.0.0-20170410110728-ff4f55a20633
go: downloading gopkg.in/square/go-jose.v2 v2.0.0-20180411045311-89060dee6a84
go: finding github.com/coreos/go-systemd v0.0.0-20180511133405-39ca1b05acc7
go: finding github.com/opencontainers/go-digest v0.0.0-20170106003457-a6d0ee40d420
go: finding github.com/vishvananda/netlink v0.0.0-20171020171820-b2de5d10e38e
go: finding k8s.io/utils v0.0.0-20190221042446-c2654d5206da
go: finding github.com/kubernetes/kubernetes/staging/src/k8s.io/cloud-provider v0.0.0-20190816231410-2d3c76f9091b
go: finding github.com/godbus/dbus v0.0.0-20151105175453-c7fdd8b5cd55
go: finding github.com/vishvananda/netns v0.0.0-20171111001504-be1fbeda1936
go: finding github.com/golang/groupcache v0.0.0-20160516000752-02826c3e7903
go: finding github.com/opencontainers/selinux v0.0.0-20170621221121-4a2974bf1ee9
build tkestack.io/gpu-manager/cmd/manager: cannot load github.com/containernetworking/cni/libcni: github.com/containernetworking/cni@v0.6.0: Get https://proxy.golang.org/github.com/containernetworking/cni/@v/v0.6.0.zip: dial tcp 216.58.200.241:443: i/o timeout
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 1`

操作系统：ubuntu 18.04
go版本：1.13.3

**Comment by mYmNeo** [comment]
It's your network problem. Try to use a suitable GO_PROXY
