### ISSUE TITLE
如何收集GPU  metrics

### ISSUE THREAD

**Issue by SolarisYan** [tkestack/gpu-manager#23]
使用gpu-manager的情况下，用 NVIDIA Data Center GPU Manager (DCGM) 不能收集到 gpu 相关的metric,请问这种情况下应该如何采集 metric到 promethus？

**Comment by mYmNeo** [comment]
gpu-manager provides basic metric in :5678/metric path.

**Comment by xs233** [comment]
How to use the gpu-manager metric?
