### ISSUE TITLE
GPU Manager not enforcing memory limits on gpu processes

### ISSUE THREAD

**Issue by Califax** [tkestack/gpu-manager#25]
Hello, I am running GPU manager and I set a max memory of tencent.com/vcuda-memory:  10 but this is not being enforced at the application level. My process can requests more gpu memory than this and nothing is done about it. 
nvidia-smi shows
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     27678      C   ...ath=/some/path  5231MiB |
+-----------------------------------------------------------------------------+

Should the process not be killed or otherwise limited? I am using a pytorch model process.

**Comment by mYmNeo** [comment]
Set environment LOG_LEVEL=5 before your application start, then post the log. Besides manager will not force kill application, it just return the error code out of memory.

**Comment by Califax** [comment]
I noticed when I submit a job where it works such as using the gpu burn test docker I see logs about the vcuda controller. It also appears to limit the memory to the correct number of tencents. Would setting the LD_LIBRARY_PTH in the node cause the image to not utilize the wrapped vcuda libraries? I set it to /usr/local/cuda/lib64. I ask as I do this for the deployments where gpu memory exceeded set limits and I did not see any logs about vcuda. I don't have any logs to share because it just mentions it is checking for which pods need gpus.

**Comment by mYmNeo** [comment]
> I noticed when I submit a job using the gpu stress test docker image (https://hub.docker.com/r/chrstnhntschl/gpu_burn/) I see logs mentioning the vcuda controller. It also appears to limit the memory to the correct number of tencents correctly. However I don't see these logs in my other pods where it did not limit memory work correctly. Would setting the LD_LIBRARY_PTH in the pod cause the image to not utilize the wrapped vcuda libraries? I set it to /usr/local/cuda/lib64 and these are the scenarios it doesn't limit memory.
> 
> I don't have any logs to share for these pods that exceed limitations. I only see logs just checking whether the pods need a gpu or not even with later log level.

The gpu-manager will set LD_LIBRARY_PATH in your container environments.If you override this environment, that means your application is bypassing the controller.The correct way is that put your library search path behind the original one.

**Comment by mYmNeo** [comment]
@Califax The environment should be LOGGER_LEVEL=5, I misspelled a wrong one in the last commit.
