### ISSUE TITLE
non-root containers can not run nvidia-smi

### ISSUE THREAD

**Issue by NoahIronMan** [tkestack/gpu-manager#26]
Everything is ok when i use root container.
But "nvidia-smi" has no return when i use non-root container.

**Comment by mYmNeo** [comment]
What's your pod template? Did you use fraction resource of GPU device?

**Comment by NoahIronMan** [comment]
I used same pod template. The only difference is docker image. I add "USER xxx" at the end of image nvidia/cuda. The Dockerfile is just like following:
`FROM nvidia/cuda:10.0-base-centos7`
`USER test`

[test@vgpu-97fcc88f8-qbqsv /]$ whoami
test
[test@vgpu-97fcc88f8-qbqsv /]$ nvidia-smi

**Comment by mYmNeo** [comment]
> I used same pod template. The only difference is docker image. I add "USER xxx" at the end of image nvidia/cuda. The Dockerfile is just like following:
> 
> ```
> FROM nvidia/cuda:10.0-base-centos7
> USER test
> ```
> 
> Pod template:
> 
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: vgpu
>   labels:
>     app: vgpu
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: vgpu
>   template:
>     metadata:
>       labels:
>         app: vgpu
>     spec:
>       containers:
>       - name: test
>         image: nvidia/cuda:10.0-base-centos7
>         resources:
>           limits:
>             tencent.com/vcuda-core: 30
>             tencent.com/vcuda-memory: 10
>           requests:
>             tencent.com/vcuda-core: 30
>             tencent.com/vcuda-memory: 10
> ```
> 
> ```
> [test@vgpu-97fcc88f8-qbqsv /]$ whoami
> test
> [test@vgpu-97fcc88f8-qbqsv /]$ nvidia-smi
>          ////  hang and no return
> ```

Got it. It's a known issue about non-root user can't communicate to gpu-manager. We'll release a new version to fix this.

**Comment by Jack47** [comment]
>  It's a known issue about non-root user can't communicate to gpu-manager. We'll release a new version to fix this.

Did you guys have plan for this? 

Or may you give some clues, would like to contribute a pr for this issue

**Comment by mYmNeo** [comment]
> > It's a known issue about non-root user can't communicate to gpu-manager. We'll release a new version to fix this.
> 
> Did you guys have plan for this?
> 
> Or may you give some clues, would like to contribute a pr for this issue @mYmNeo

A week later, we'll release a new version to support CRI runtime api. At the same time, we'll fix it.

**Comment by mYmNeo** [comment]
We released a new version including this fix. Welcome to have try.

**Comment by Jack47** [comment]
thanks for your quick response, this works like a charm! @mYmNeo
