### ISSUE TITLE
vcuda-controller can not limit GPU utilization

### ISSUE THREAD

**Issue by NoahIronMan** [tkestack/gpu-manager#29]
GPU-manager 1.1.0 can limit GPU utilization, i have installed vcuda-controller.

```+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:18:00.0 Off |                    0 |
| N/A   69C    P0    54W /  70W |   2102MiB / 15079MiB |     42%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            On   | 00000000:86:00.0 Off |                    0 |
| N/A   65C    P0    58W /  70W |   2110MiB / 15079MiB |     70%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0   3460176      C   python3                                      523MiB |
|    0   3460231      C   python3                                      523MiB |
|    0   3460358      C   python3                                      523MiB |
|    0   3460379      C   python3                                      523MiB |
|    1   3460340      C   python3                                      523MiB |
|    1   3460448      C   python3                                      523MiB |
|    1   3460506      C   python3                                      531MiB |
|    1   3460583      C   python3                                      523MiB |
+-----------------------------------------------------------------------------+
```
The log of Pod:
```/tmp/cuda-control/src/hijack_call.c:277 util: 85, up_limit: 24,  share: 1120205, cur: 1310720
/tmp/cuda-control/src/hijack_call.c:277 util: 85, up_limit: 24,  share: 929690, cur: 1310720
/tmp/cuda-control/src/hijack_call.c:277 util: 85, up_limit: 24,  share: 739175, cur: 1310720
/tmp/cuda-control/src/hijack_call.c:277 util: 85, up_limit: 24,  share: 548660, cur: 1096358
/tmp/cuda-control/src/hijack_call.c:277 util: 85, up_limit: 24,  share: 358145, cur: 671260
/tmp/cuda-control/src/hijack_call.c:277 util: 85, up_limit: 24,  share: 167630, cur: 164177
/tmp/cuda-control/src/hijack_call.c:277 util: 85, up_limit: 24,  share: 0, cur: -7459
/tmp/cuda-control/src/hijack_call.c:277 util: 0, up_limit: 24,  share: 29491, cur: 22032
/tmp/cuda-control/src/hijack_call.c:277 util: 0, up_limit: 24,  share: 58982, cur: 58557
/tmp/cuda-control/src/hijack_call.c:277 util: 0, up_limit: 24,  share: 88473, cur: 83669
/tmp/cuda-control/src/hijack_call.c:277 util: 43, up_limit: 24,  share: 571337, cur: 568058
/tmp/cuda-control/src/hijack_call.c:277 util: 43, up_limit: 24,  share: 552854, cur: 552652
/tmp/cuda-control/src/hijack_call.c:277 util: 43, up_limit: 24,  share: 534371, cur: 533840
/tmp/cuda-control/src/hijack_call.c:277 util: 43, up_limit: 24,  share: 515888, cur: 507754
/tmp/cuda-control/src/hijack_call.c:277 util: 43, up_limit: 24,  share: 497405, cur: 490251
/tmp/cuda-control/src/hijack_call.c:277 util: 43, up_limit: 24,  share: 478922, cur: 478331
/tmp/cuda-control/src/hijack_call.c:277 util: 43, up_limit: 24,  share: 460439, cur: 460297
/tmp/cuda-control/src/hijack_call.c:277 util: 0, up_limit: 24,  share: 489930, cur: 489114
/tmp/cuda-control/src/hijack_call.c:277 util: 0, up_limit: 24,  share: 519421, cur: 518216
```

**Comment by mYmNeo** [comment]
Please use nvidia-smi pmon -i <card index> to see the statistics gpu information, and paste the result.

PS: What's kind of your program? Training or predication?

**Comment by NoahIronMan** [comment]
``` 
nvidia-smi pmon 
# gpu        pid  type    sm   mem   enc   dec   command
# Idx          #   C/G     %     %     %     %   name
    0    3460176     C    11     5     0     0   python3
    0    3460176     C    35    22     0     0   python3
    0    3460176     C    43    31     0     0   python3
    0    3460176     C    38    28     0     0   python3
    0    3460176     C    32    23     0     0   python3
```
I use python to do some trainging.

**Comment by mYmNeo** [comment]
> ```
> nvidia-smi pmon 
> # gpu        pid  type    sm   mem   enc   dec   command
> # Idx          #   C/G     %     %     %     %   name
>     0    3460176     C    11     5     0     0   python3
>     0    3460176     C    35    22     0     0   python3
>     0    3460176     C    43    31     0     0   python3
>     0    3460176     C    38    28     0     0   python3
>     0    3460176     C    32    23     0     0   python3
> ```
> 
> I use python to do some trainging.

According to these output, what's your limit to this pod?

**Comment by NoahIronMan** [comment]
···
Limits:
      tencent.com/vcuda-core:    24
      tencent.com/vcuda-memory:  13
    Requests:
      tencent.com/vcuda-core:    24
      tencent.com/vcuda-memory:  13
···

**Comment by NoahIronMan** [comment]
> > ```
> > nvidia-smi pmon 
> > # gpu        pid  type    sm   mem   enc   dec   command
> > # Idx          #   C/G     %     %     %     %   name
> >     0    3460176     C    11     5     0     0   python3
> >     0    3460176     C    35    22     0     0   python3
> >     0    3460176     C    43    31     0     0   python3
> >     0    3460176     C    38    28     0     0   python3
> >     0    3460176     C    32    23     0     0   python3
> > ```
> > 
> > 
> > I use python to do some trainging.
> 
> According to these output, what's your limit to this pod?
```
Annotations:        tencent.com/gpu-assigned: true
                    tencent.com/predicate-gpu-idx-0: 0
                    tencent.com/predicate-node: sh-office-10-5-42-101
                    tencent.com/predicate-time: 1591070446744587529
                    tencent.com/vcuda-core-limit: 24
    Limits:
      tencent.com/vcuda-core:    24
      tencent.com/vcuda-memory:  13
    Requests:
      tencent.com/vcuda-core:    24
      tencent.com/vcuda-memory:  13
```

**Comment by mYmNeo** [comment]
> > > ```
> > > nvidia-smi pmon 
> > > # gpu        pid  type    sm   mem   enc   dec   command
> > > # Idx          #   C/G     %     %     %     %   name
> > >     0    3460176     C    11     5     0     0   python3
> > >     0    3460176     C    35    22     0     0   python3
> > >     0    3460176     C    43    31     0     0   python3
> > >     0    3460176     C    38    28     0     0   python3
> > >     0    3460176     C    32    23     0     0   python3
> > > ```
> > > 
> > > 
> > > I use python to do some trainging.
> > 
> > 
> > According to these output, what's your limit to this pod?
> 
> ```
> Annotations: 
>     tencent.com/gpu-assigned: true
>     tencent.com/predicate-gpu-idx-0: 0
>     tencent.com/predicate-node: sh-office-10-5-42-101
>     tencent.com/predicate-time: 1591070446744587529
>     tencent.com/vcuda-core-limit: 24
> 
>     Limits:
>       tencent.com/vcuda-core:    24
>       tencent.com/vcuda-memory:  13
>     Requests:
>       tencent.com/vcuda-core:    24
>       tencent.com/vcuda-memory:  13
> ```

Remove annotation `tencent.com/vcuda-core-limit: 24` and try again? The annotation `tencent.com/vcuda-core-limit` means you enable dynamic utilization control but it seems that you want a hard limit.

**Comment by NoahIronMan** [comment]
I didn't add tencent.com/vcuda-core-limit in the annotation at first. The result was same. So i add this according to the README.md.
[https://github.com/tkestack/gpu-manager/blob/master/README.md#pod-template-example](url)

**Comment by NoahIronMan** [comment]
> > > > ```
> > > > nvidia-smi pmon 
> > > > # gpu        pid  type    sm   mem   enc   dec   command
> > > > # Idx          #   C/G     %     %     %     %   name
> > > >     0    3460176     C    11     5     0     0   python3
> > > >     0    3460176     C    35    22     0     0   python3
> > > >     0    3460176     C    43    31     0     0   python3
> > > >     0    3460176     C    38    28     0     0   python3
> > > >     0    3460176     C    32    23     0     0   python3
> > > > ```
> > > > 
> > > > 
> > > > I use python to do some trainging.
> > > 
> > > 
> > > According to these output, what's your limit to this pod?
> > 
> > 
> > ```
> > Annotations: 
> >     tencent.com/gpu-assigned: true
> >     tencent.com/predicate-gpu-idx-0: 0
> >     tencent.com/predicate-node: sh-office-10-5-42-101
> >     tencent.com/predicate-time: 1591070446744587529
> >     tencent.com/vcuda-core-limit: 24
> > 
> >     Limits:
> >       tencent.com/vcuda-core:    24
> >       tencent.com/vcuda-memory:  13
> >     Requests:
> >       tencent.com/vcuda-core:    24
> >       tencent.com/vcuda-memory:  13
> > ```
> 
> Remove annotation `tencent.com/vcuda-core-limit: 24` and try again? The annotation `tencent.com/vcuda-core-limit` means you enable dynamic utilization control but it seems that you want a hard limit.

**Comment by NoahIronMan** [comment]
@mYmNeo Can vcuda-controller give QoS guaranteed to each pod?

**Comment by mYmNeo** [comment]
> @mYmNeo Can vcuda-controller give QoS guaranteed to each pod?

In user level, it do its best to control the utilization, to do the strict limitation, only NVIDIA does.

**Comment by NoahIronMan** [comment]
I see.Thank you!

**Comment by zxt620** [comment]
the problem of  you ,does it resolved?

**Comment by hzliangbin** [comment]
@zxt620 @jingcheng88 any progress?
