### ISSUE TITLE
请问下有相应的实现文档吗？

### ISSUE THREAD

**Issue by XuHaoIgeneral** [tkestack/gpu-manager#3]
初略的看了一下yaml文件，大概了解了运行架构。但是请问具体实现有相应的介绍吗？

**Comment by knightXun** [comment]
gpu-manager应该不是最核心的东西，vcuda-controller才是。我推测阿里云gpu虚拟化也类似vcuda-controller

**Comment by XuHaoIgeneral** [comment]
> gpu-manager应该不是最核心的东西，vcuda-controller才是。我推测阿里云gpu虚拟化也类似vcuda-controller

好的，多谢。
