### ISSUE TITLE
Cannot deploy the gpu-manager with errors

### ISSUE THREAD

**Issue by XavierMoo** [tkestack/gpu-manager#30]
I tried to deploy gpu-manager with command below:
`kubectl apply -f gpu-manager.yaml` .
There I got Error.
After read  #7 , I mounted /root/.kube/ to deamonset, 
and I got some additional information in logs, but still can't run properly.
Here are the informations of **gpu-manager.WARRING**:
>E0609 07:18:41.624501    1373 server.go:132] Unable to set Type=notify in systemd service file?
>E0609 07:18:42.676956    1373 tree.go:337] No topology level found at 0
>W0609 07:18:42.688012    1373 allocator.go:1298] Failed to read from checkpoint due to key is not found

Our env:

CentOS Linux release 7.8.2003 (Core)
3.10.0-1127.8.2.el7.x86_64
kubernetes: 1.14.1
kubeflow:1.0
img: v1.0.0  

touch me if more information is needed.

**Comment by mYmNeo** [comment]
> I tried to deploy gpu-manager with command below:
> `kubectl apply -f gpu-manager.yaml` .
> There I got Error.
> After read #7 , I mounted /root/.kube/ to deamonset,
> and I got some additional information in logs, but still can't run properly.
> Here are the informations of **gpu-manager.WARRING**:
> 
> > E0609 07:18:41.624501    1373 server.go:132] Unable to set Type=notify in systemd service file?
> > E0609 07:18:42.676956    1373 tree.go:337] No topology level found at 0
> > W0609 07:18:42.688012    1373 allocator.go:1298] Failed to read from checkpoint due to key is not found
> 
> Our env:
> 
> CentOS Linux release 7.8.2003 (Core)
> 3.10.0-1127.8.2.el7.x86_64
> kubernetes: 1.14.1
> kubeflow:1.0
> img: v1.0.0
> 
> touch me if more information is needed.

What do you mean by `run properly`? Did node has resources like `tencent.com/vcuda-cores`

**Comment by XavierMoo** [comment]
> 
> 
> > I tried to deploy gpu-manager with command below:
> > `kubectl apply -f gpu-manager.yaml` .
> > There I got Error.
> > After read #7 , I mounted /root/.kube/ to deamonset,
> > and I got some additional information in logs, but still can't run properly.
> > Here are the informations of **gpu-manager.WARRING**:
> > > E0609 07:18:41.624501    1373 server.go:132] Unable to set Type=notify in systemd service file?
> > > E0609 07:18:42.676956    1373 tree.go:337] No topology level found at 0
> > > W0609 07:18:42.688012    1373 allocator.go:1298] Failed to read from checkpoint due to key is not found
> > 
> > 
> > Our env:
> > CentOS Linux release 7.8.2003 (Core)
> > 3.10.0-1127.8.2.el7.x86_64
> > kubernetes: 1.14.1
> > kubeflow:1.0
> > img: v1.0.0
> > touch me if more information is needed.
> 
> What do you mean by `run properly`? Did node has resources like `tencent.com/vcuda-cores`

I didn't find resources like /tencent.com/vcuda-cores.
But it seems like that it works. 
I'll close the ticket.
