### ISSUE TITLE
CUDA 10.2 support

### ISSUE THREAD

**Issue by Ghotrix** [tkestack/gpu-manager#31]
Any plans to support CUDA 10.2?

**Comment by mYmNeo** [comment]
What's your version of `gpu-manager`? The latest releases of `v1.0.4` and `v1.10` contains the CUDA 10.2 support.

**Comment by Ghotrix** [comment]
Sorry, somehow I thought nvml headers needed by `go-nvml` package do not exist for 10.2 CUDA. The build couldn't find nvml.h and was failing.
Fixed with `export CGO_CFLAGS="-I<path_to_nvml_header>"` before `make`. Perhaps, this one should be included in the README.md.
