### ISSUE TITLE
make时，有以下问题。

### ISSUE THREAD

**Issue by Succw** [tkestack/gpu-manager#33]
[root@instance-kakwck8j ~]# cd gpu-manager-1.1.0/
[root@instance-kakwck8j gpu-manager-1.1.0]# make
hack/build.sh manager client
go: k8s.io/apimachinery@v0.17.4 requires
	k8s.io/kube-openapi@v0.0.0-20191107075043-30be4d16710a requires
	github.com/ghodss/yaml@v0.0.0-20150909031657-73d445a93680: invalid version: git fetch --unshallow -f https://github.com/ghodss/yaml in /root/go/pkg/mod/cache/vcs/5c75ad62eb9c289b6ed86c76998b4ab8c8545a841036e879d703a2bbc5fcfcea: exit status 128:
	fatal: git fetch-pack: expected shallow list
make: *** [all] Error 1

**Comment by Succw** [comment]
在go.sum中，还有其他模块无法获取。

**Comment by klzsysy** [comment]
我make成功了, `registry.forchange.cn/public/tkestack/gpu-manager:1.1.0`
