### ISSUE TITLE
When I launch gpu-manager.The vcuda-memory limit is invalid.

### ISSUE THREAD

**Issue by Lzhang-hub** [tkestack/gpu-manager#39]
when I launch gpu-manager，the log error:Unable to set Type=notify in systemd service file?  and I read the issue [https://github.com/tkestack/gpu-manager/issues/7](url)   .The difference is that the resources have been exist on the node. and I create a pod through `kubectl create -f test1.yaml` successfully， it can find in the follow picture. 
![image](https://user-images.githubusercontent.com/57925599/89514912-0cd7dc80-d809-11ea-8c17-65b10609e239.png)

![image](https://user-images.githubusercontent.com/57925599/89516049-7efcf100-d80a-11ea-901f-6dbb4aa54e5e.png)

![image](https://user-images.githubusercontent.com/57925599/89515111-43adf280-d809-11ea-8f72-04435c15242d.png)

The problem is when the pod is running ,the vcuda-memory limit is invalid. Fro example :when the pod request vcuda-memory  is 1, the actual resources used exceed this value.
![image](https://user-images.githubusercontent.com/57925599/89515581-e8c8cb00-d809-11ea-81dc-806e4c4e2bb1.png)
![image](https://user-images.githubusercontent.com/57925599/89515736-1b72c380-d80a-11ea-9313-c09cd3e72a8c.png)

**Comment by mYmNeo** [comment]
The hundred of vcuda-core means use the entire gpu card, so there is no limit.

**Comment by Lzhang-hub** [comment]
@mYmNeo But the vcuda-memory value I gave was 1, and I noticed that the vcuda-memory allocation in papers and patents is a hard limit,  is shown  in following pictures. How do I understand this.

![image](https://user-images.githubusercontent.com/57925599/89600541-dd6eb180-d894-11ea-93ca-42ff35248636.png)

![image](https://user-images.githubusercontent.com/57925599/89600519-d182ef80-d894-11ea-9024-34c6d6a61f4c.png)

**Comment by Lzhang-hub** [comment]
@mYmNeo 
This is my pod logs, I never found out what the problem was
![image](https://user-images.githubusercontent.com/57925599/89763621-7ca9d800-db25-11ea-93f7-ba9788bc8541.png)
