### ISSUE TITLE
Unable to set Type=notify in systemd service file

### ISSUE THREAD

**Issue by DeepDarkOdyssey** [tkestack/gpu-manager#40]
Just like #7,  I followed https://cloud.tencent.com/developer/article/1685122 this blog and everything works fine and all pods in running, while the gpu-manger-daemon pod logs shows it stuck at server.go: 132
![image](https://user-images.githubusercontent.com/37280638/92687158-9b41ff80-f36d-11ea-833a-42f04ea3c6f7.png)
I tried many solutions like change the drive from systemd to cgroup, it won't work. The pod is running with no response.
Meanwhile I found the extra flags that need to be set from https://github.com/tkestack/gpu-manager/blob/master/docs/faq.md, but when I configured the gpu-manager like this:
![image](https://user-images.githubusercontent.com/37280638/92687455-26bb9080-f36e-11ea-8214-4ba82c6d8606.png)
the pod can't get started, it seems like the extra flags here directly pass to the gpu-manager as a call option but it doesn't has such option named "cgroup-driver".  What did I missing?

**Comment by mYmNeo** [comment]
gpu-manager log is stored at host volume `/etc/gpu-manager/logs`. The stdout log is not the gpu-manager‘s, can you provide the gpu-manager.INFO？

**Comment by DeepDarkOdyssey** [comment]
> gpu-manager log is stored at host volume `/etc/gpu-manager/logs`. The stdout log is not the gpu-manager‘s, can you provide the gpu-manager.INFO？

I disabled nvidia as default docker runtime and everything works fine now, the pod can be asigned with specific gpu memory, thanks for this amazing work. But still, the error log from the container stdout is there, and I'm still confused with the extra flags from the faq.md.
And by the way, somehow  running a gpu related training job in container from image menghe.tencentcloudcr.com/public/tensorflow-gputest:0.2 takes couple of minutes to get started, and other image build by myself works just fine.

**Comment by mYmNeo** [comment]
> > gpu-manager log is stored at host volume `/etc/gpu-manager/logs`. The stdout log is not the gpu-manager‘s, can you provide the gpu-manager.INFO？
> 
> I disabled nvidia as default docker runtime and everything works fine now, the pod can be asigned with specific gpu memory, thanks for this amazing work. But still, the error log from the container stdout is there, and I'm still confused with the extra flags from the faq.md.
> And by the way, somehow running a gpu related training job in container from image menghe.tencentcloudcr.com/public/tensorflow-gputest:0.2 takes couple of minutes to get started, and other image build by myself works just fine.

What's your problem with FAQ? Is there something that is not described clearly or misunderstanding, we'll improve it if you could point it out.

I have no idea about this image `menghe.tencentcloudcr.com/public/tensorflow-gputest:0.2`, maybe you can rebuild it by the Dockerfile they provides if possible.

**Comment by fanhaozzu** [comment]
you can exec the cmd：nvidia-modprobe -u -c=0

**Comment by pandaoknight** [comment]
After l install nvidia-container-toolkit the 'Unable to set Type=notify in systemd service file problem' disapeared.
