### ISSUE TITLE
make img failed

### ISSUE THREAD

**Issue by lolo-pop** [tkestack/gpu-manager#43]
It failed when I executed the `make img` command. 
I have used a proxy: `go env -w GO111MODULE=on`
`go env -w GOPROXY=https://goproxy.io,direct`
How should I solve it, or can you provide an image for me to `docker pull`.
![image](https://user-images.githubusercontent.com/16383423/94407314-e483b300-01a5-11eb-84c3-8fe0c715dd95.png)

**Comment by ChAnYaNG97** [comment]
same problem, did you finally solve it?

**Comment by ZinuoCai** [comment]
You can set the proxy in Dockerfile like below.
```
ENV GOPROXY [your proxy address]
```
