### ISSUE TITLE
gpu manager log store cause disk full

### ISSUE THREAD

**Issue by little-guy-lxr** [tkestack/gpu-manager#52]
now gpu manager log without clean feature that cause too many log files occupy disk. 

log dir default  is host path /etc/gpu-manager/log

so recommend adding log rotate, for example:  I could config log could store one week,  log belong one week ago can be delete automatically

**Comment by little-guy-lxr** [comment]
//	-logtostderr=false
//		Logs are written to standard error instead of to files.

recommend add a feature allow user to config logtostderr
![image](https://user-images.githubusercontent.com/26966109/100825874-05ad9c00-3494-11eb-87b6-471ecf77e611.png)

add a para logtostderr

**Comment by mYmNeo** [comment]
We provide custom flags at https://github.com/tkestack/gpu-manager/blob/master/build/start.sh#L13
