### ISSUE TITLE
if resquet whole or multi gpu card metric container_request_gpu_memory is 0 

### ISSUE THREAD

**Issue by little-guy-lxr** [tkestack/gpu-manager#58]
if pod resource request is blow without vcuda-memory request
resources:
            limits:
              tencent.com/vcuda-core: "100"

get metric container_request_gpu_memory is 0 

container_request_gpu_memory{container_name="gpu-benchmark",namespace="gpu-hh-ll",node="10.0.131.150",pod_name="gpu-benchmark-1-5fdbd46b77-cp5xx",req_of_gpu_memory="total"} 0
container_request_gpu_memory{container_name="gpu-benchmark",namespace="gpu-hh-ll",node="10.0.131.150",pod_name="gpu-benchmark-6dd6d787b5-5z65m",req_of_gpu_memory="total"} 0

expect:
the sum of gpus' mem

**Comment by mYmNeo** [comment]
req_of_gpu_memory is read from pod spec

**Comment by little-guy-lxr** [comment]
> req_of_gpu_memory is read from pod spec

I know, if user request whole or muli gpu, pod spec request mem doesn't work, the pod could use whole gpu mem, so I think container_request_gpu_memory should be the sum of gpus' mem. and in this case,  if user want to calculate the utilization of gpu mem , the container_request_gpu_memory  is zero , it would has problem. 

 utilization = container_gpu_memory_total / container_request_gpu_memory

**Comment by mYmNeo** [comment]
> > req_of_gpu_memory is read from pod spec
> 
> I know, if user request whole or muli gpu, pod spec request mem doesn't work, the pod could use whole gpu mem, so I think container_request_gpu_memory should be the sum of gpus' mem. and in this case, if user want to calculate the utilization of gpu mem , the container_request_gpu_memory is zero , it would has problem.
> 
> utilization = container_gpu_memory_total / container_request_gpu_memory

We can improve that in a future release.

**Comment by mYmNeo** [comment]
We released a version to support this, please check out

**Comment by little-guy-lxr** [comment]
> We released a version to support this, please check out

which version or branch , please provide , thanks
