### ISSUE TITLE
metric add process's gpu usage(pid) in container 

### ISSUE THREAD

**Issue by little-guy-lxr** [tkestack/gpu-manager#60]
could gpu-manager metric export process's gpu usage(pid) in container if user want to get gpu usage of process(pid). 

in metric source code ,  nvml could get process gpu information, but didn't export it to prometheus

**Comment by mYmNeo** [comment]
> could gpu-manager metric export process's gpu usage(pid) in container if user want to get gpu usage of process(pid).
> 
> in metric source code , nvml could get process gpu information, but didn't export it to prometheus

1. Pid is sensitive information, should not export to prometheus.
2. Pids in nvml call are in host pid namespace, not in user namespace
