### ISSUE TITLE
At present, what types of nvidia cards are supported by gpu-manager container-level virtualization? For example: mainstream RTX, GTX and Tesla series mainstream cards 2080ti, 3090, 3080, Thank you

### ISSUE THREAD

**Issue by ACK-lcn** [tkestack/gpu-manager#64]
At present, what types of nvidia cards are supported by gpu-manager container-level virtualization? For example: mainstream RTX, GTX and Tesla series mainstream cards 2080ti, 3090, 3080,
Thank you

**Comment by mYmNeo** [comment]
Any card which its architecture after Kepler is supported.
