### ISSUE TITLE
undefined symbol: cuIpcOpenMemHandle_v2

### ISSUE THREAD

**Issue by GolemHerry** [tkestack/gpu-manager#68]
## Problem
> It works when I start a container with `docker run`. 
> But I met this error when I start with `kubectl create -f `

```shell
Traceback (most recent call last):
  File "pycuda_test.py", line 1, in <module>
    import pycuda._driver
ImportError: /usr/local/lib/python3.8/dist-packages/pycuda/_driver.cpython-38-x86_64-linux-gnu.so: undefined symbol: cuIpcOpenMemHandle_v2
```

```Dockerfile
FROM nvidia/cuda:11.1.1-devel-ubuntu20.04

COPY pycuda_test.py /app/pycuda_test.py
RUN apt install python3 python3-pip -y
RUN pip3 install pycuda six -i https://pypi.tuna.tsinghua.edu.cn/simple

WORKDIR /app/

CMD ["python3", "pycuda_test.py"]
```

## GPU Info
```shell
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 980     Off  | 00000000:01:00.0 Off |                  N/A |
|  5%   46C    P8    26W / 195W |      0MiB /  4043MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 980     Off  | 00000000:04:00.0 Off |                  N/A |
|  0%   34C    P8    16W / 195W |      0MiB /  4043MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

## System Info
```shell
System Info:
  Machine ID:                 0b7685819b5248e486bbec1fb08b83ab
  System UUID:                E2E09520-D7FC-11DD-9E68-D017C29AD90D
  Boot ID:                    c730a1b0-4ace-4d5c-8ba2-af71bf636601
  Kernel Version:             3.10.0-1160.11.1.el7.x86_64
  OS Image:                   CentOS Linux 7 (Core)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://20.10.2
  Kubelet Version:            v1.16.9
  Kube-Proxy Version:         v1.16.9
```

## gpu-manager image
> tkestack/gpu-manager:v1.1.2

**Comment by mYmNeo** [comment]
> ## Problem
> > It works when I start a container with `docker run`.
> > But I met this error when I start with `kubectl create -f `
> 
> ```shell
> Traceback (most recent call last):
>   File "pycuda_test.py", line 1, in <module>
>     import pycuda._driver
> ImportError: /usr/local/lib/python3.8/dist-packages/pycuda/_driver.cpython-38-x86_64-linux-gnu.so: undefined symbol: cuIpcOpenMemHandle_v2
> ```
> 
> ```dockerfile
> FROM nvidia/cuda:11.1.1-devel-ubuntu20.04
> 
> COPY pycuda_test.py /app/pycuda_test.py
> RUN apt install python3 python3-pip -y
> RUN pip3 install pycuda six -i https://pypi.tuna.tsinghua.edu.cn/simple
> 
> WORKDIR /app/
> 
> CMD ["python3", "pycuda_test.py"]
> ```
> 
> ## GPU Info
> ```shell
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 980     Off  | 00000000:01:00.0 Off |                  N/A |
> |  5%   46C    P8    26W / 195W |      0MiB /  4043MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   1  GeForce GTX 980     Off  | 00000000:04:00.0 Off |                  N/A |
> |  0%   34C    P8    16W / 195W |      0MiB /  4043MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+
> ```
> 
> ## System Info
> ```shell
> System Info:
>   Machine ID:                 0b7685819b5248e486bbec1fb08b83ab
>   System UUID:                E2E09520-D7FC-11DD-9E68-D017C29AD90D
>   Boot ID:                    c730a1b0-4ace-4d5c-8ba2-af71bf636601
>   Kernel Version:             3.10.0-1160.11.1.el7.x86_64
>   OS Image:                   CentOS Linux 7 (Core)
>   Operating System:           linux
>   Architecture:               amd64
>   Container Runtime Version:  docker://20.10.2
>   Kubelet Version:            v1.16.9
>   Kube-Proxy Version:         v1.16.9
> ```
> 
> ## gpu-manager image
> > tkestack/gpu-manager:v1.1.2

vcuda has not supported cuda-11.1, we'll update vcuda project in the future.

**Comment by GolemHerry** [comment]
> > ## Problem
> > > It works when I start a container with `docker run`.
> > > But I met this error when I start with `kubectl create -f `
> > 
> > 
> > ```shell
> > Traceback (most recent call last):
> >   File "pycuda_test.py", line 1, in <module>
> >     import pycuda._driver
> > ImportError: /usr/local/lib/python3.8/dist-packages/pycuda/_driver.cpython-38-x86_64-linux-gnu.so: undefined symbol: cuIpcOpenMemHandle_v2
> > ```
> > 
> > 
> > ```dockerfile
> > FROM nvidia/cuda:11.1.1-devel-ubuntu20.04
> > 
> > COPY pycuda_test.py /app/pycuda_test.py
> > RUN apt install python3 python3-pip -y
> > RUN pip3 install pycuda six -i https://pypi.tuna.tsinghua.edu.cn/simple
> > 
> > WORKDIR /app/
> > 
> > CMD ["python3", "pycuda_test.py"]
> > ```
> > 
> > 
> > ## GPU Info
> > ```shell
> > +-----------------------------------------------------------------------------+
> > | NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
> > |-------------------------------+----------------------+----------------------+
> > | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> > | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> > |                               |                      |               MIG M. |
> > |===============================+======================+======================|
> > |   0  GeForce GTX 980     Off  | 00000000:01:00.0 Off |                  N/A |
> > |  5%   46C    P8    26W / 195W |      0MiB /  4043MiB |      0%      Default |
> > |                               |                      |                  N/A |
> > +-------------------------------+----------------------+----------------------+
> > |   1  GeForce GTX 980     Off  | 00000000:04:00.0 Off |                  N/A |
> > |  0%   34C    P8    16W / 195W |      0MiB /  4043MiB |      0%      Default |
> > |                               |                      |                  N/A |
> > +-------------------------------+----------------------+----------------------+
> > 
> > +-----------------------------------------------------------------------------+
> > | Processes:                                                                  |
> > |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> > |        ID   ID                                                   Usage      |
> > |=============================================================================|
> > |  No running processes found                                                 |
> > +-----------------------------------------------------------------------------+
> > ```
> > 
> > 
> > ## System Info
> > ```shell
> > System Info:
> >   Machine ID:                 0b7685819b5248e486bbec1fb08b83ab
> >   System UUID:                E2E09520-D7FC-11DD-9E68-D017C29AD90D
> >   Boot ID:                    c730a1b0-4ace-4d5c-8ba2-af71bf636601
> >   Kernel Version:             3.10.0-1160.11.1.el7.x86_64
> >   OS Image:                   CentOS Linux 7 (Core)
> >   Operating System:           linux
> >   Architecture:               amd64
> >   Container Runtime Version:  docker://20.10.2
> >   Kubelet Version:            v1.16.9
> >   Kube-Proxy Version:         v1.16.9
> > ```
> > 
> > 
> > ## gpu-manager image
> > > tkestack/gpu-manager:v1.1.2
> 
> vcuda has not supported cuda-11.1, we'll update vcuda project in the future.

Really thank you for your reply, and may I ask how soon will the support be updated.
