### ISSUE TITLE
LD_LIBRARY_PATH 在k8s环境被替换，应该是追加

### ISSUE THREAD

**Issue by Moersity** [tkestack/gpu-manager#69]
```sh
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
镜像中原本是/xxx/lib:/usr/local/lib, 被替换为了
LD_LIBRARY_PATH=/usr/local/nvidia/lib64

**Comment by GolemHerry** [comment]
> ```shell
> Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> 镜像中原本是/xxx/lib:/usr/local/lib, 被替换为了
> LD_LIBRARY_PATH=/usr/local/nvidia/lib64

vCUDA能实现资源隔离的原因是劫持了应用对 CUDA Driver API 的调用
```shell
root@pycuda:/app# ldd /usr/local/lib/python3.8/dist-packages/pycuda/_driver.cpython-38-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007fff37187000)
--->    libcuda.so.1 => /usr/local/nvidia/lib64/libcuda.so.1 (0x00007f0c3edf1000)
	libcurand.so.10 => /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcurand.so.10 (0x00007f0c3a27d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0c3a09c000)
	libgcc_s.so.1 => /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0c3a081000)
	libpthread.so.0 => /usr/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0c3a05e000)
	libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007f0c39e6c000)
	librt.so.1 => /usr/lib/x86_64-linux-gnu/librt.so.1 (0x00007f0c39e5f000)
	libdl.so.2 => /usr/lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0c39e59000)
	libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007f0c39d0a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0c3f1f3000)
```

**Comment by zwpaper** [comment]
Device Plugin 无法感知容器内环境变量，所以没法做到追加，只能修改。

另外可以考虑在 Pod 的 Yaml 定义指定 `LD_LIBRARY_PATH` 环境变量，并把 `/usr/local/nvidia/lib64` 放在最前面，Pod 的定义优先级更高，就不会被修改

**Comment by Moersity** [comment]
> Device Plugin 无法感知容器内环境变量，所以没法做到追加，只能替换。
> 
> 另外可以考虑在 Pod 的 Yaml 定义指定 `LD_LIBRARY_PATH` 环境变量，并把 `�/usr/local/nvidia/lib64` 放在最前面，Pod 的定义优先级更高，就不会被替换

我目前也是这样做的，非常感谢

**Comment by seanchen022** [comment]
> Device Plugin 无法感知容器内环境变量，所以没法做到追加，只能替换。
> 
> 另外可以考虑在 Pod 的 Yaml 定义指定 `LD_LIBRARY_PATH` 环境变量，并把 `�/usr/local/nvidia/lib64` 放在最前面，Pod 的定义优先级更高，就不会被替换
那如果镜像里本身有 LD_LIBRARY_PATH 这个环境变量该怎么办呢，因为 gpu-manager会被直接替换 LD_LIBRARY_PATH 导致镜像里设置的  LD_LIBRARY_PATH 消失了从而导致容器运行错误，这种有解决办法吗

**Comment by seanchen022** [comment]
> Device Plugin 无法感知容器内环境变量，所以没法做到追加，只能替换。
> 
> 另外可以考虑在 Pod 的 Yaml 定义指定 `LD_LIBRARY_PATH` 环境变量，并把 `�/usr/local/nvidia/lib64` 放在最前面，Pod 的定义优先级更高，就不会被替换

另外可以考虑在 Pod 的 Yaml 定义指定 LD_LIBRARY_PATH 环境变量，并把 �/usr/local/nvidia/lib64 放在最前面，Pod 的定义优先级更高，就不会被替换
那如果镜像里本身有 LD_LIBRARY_PATH 这个环境变量该怎么办呢，因为 gpu-manager会被直接替换 LD_LIBRARY_PATH 导致镜像里设置的 LD_LIBRARY_PATH 消失了从而导致容器运行错误，这种有解决办法吗
