### ISSUE TITLE
Run with minikube on laptop

### ISSUE THREAD

**Issue by msaadatkh** [tkestack/gpu-manager#72]
Can't run this project on a laptop with minikube(docker driver).
Does this project work in a specific environment or infrastructure?

**Comment by mYmNeo** [comment]
> Can't run this project on a laptop with minikube(docker driver).
> Does this project work in a specific environment or infrastructure?

I'm not familiar with `minikube`, but gpu-manager need a privileged permission with host device access etc. You can try the script `hack/local-up-cluster.sh` in kubernetes project.

**Comment by MSaadatt** [comment]
Thanks for your answer.

One another question: Is build and deploy [gpu-manager](https://github.com/tkestack/gpu-manager) is enough or I need to run [gpu-admission](https://github.com/tkestack/gpu-admission) or another thing separately?

**Comment by mYmNeo** [comment]
> Thanks for your answer.
> 
> One another question: Build and deploy [gpu-manager](https://github.com/tkestack/gpu-manager) is enough or I need to run [gpu-admission](https://github.com/tkestack/gpu-admission) or another thing separately?

It depends on you. If you want some pod share on one card, you need run gpu-admission, otherwise only gpu-manager can work.
