### ISSUE TITLE
vcuda-core limit don't work

### ISSUE THREAD

**Issue by ZeoSophia** [tkestack/gpu-manager#73]
My two pods configurations:
![image](https://user-images.githubusercontent.com/36197596/109805520-80867e80-7c5e-11eb-9b9e-bc48fbc8eb9f.png)
![image](https://user-images.githubusercontent.com/36197596/109805536-88462300-7c5e-11eb-9fd0-173b3d3d85f6.png)
I think that the cuda-core with 80 will complete early than cuda-core with 20 ,but in fact ,they complete almost at the same time 
And this is nvidia-smi pmon -s u -d 1 showed:
![image](https://user-images.githubusercontent.com/36197596/109805919-fbe83000-7c5e-11eb-8546-b98a201fcece.png)
the image is just a code of matrix multiplication(4096*4096)
But the cuda-core limit works in AlexNet , So what should I do?

**Comment by mYmNeo** [comment]
For small cuda calculation, there is not enough space to limit the usage, but for training app there is

**Comment by ZeoSophia** [comment]
> 对于小型cuda计算，没有足够的空间来限制使用，但是对于训练应用程序来说
If I want to implement the restriction in small CUDA computation, what should I do or which part should I change, based on gpu-manager?

**Comment by mYmNeo** [comment]
> > 对于小型cuda计算，没有足够的空间来限制使用，但是对于训练应用程序来说
> > I see the log, the delta is always 0.And there is not the use of grid or blocks.
> > ![image](https://user-images.githubusercontent.com/36197596/110413328-9fef3280-80c8-11eb-9a5e-dce5068e23ea.png)
> 
> If I want to implement the restriction in small CUDA computation, what should I do or which part should I change, based on gpu-manager?

CUDA limit is based on project [vcuda-controller](https://github.com/tkestack/vcuda-controller)

**Comment by ZeoSophia** [comment]
> > > 对于小型cuda计算，没有足够的空间来限制使用，但是对于训练应用程序来说。
> > > 我看到的日志是，增量始终为0。并且没有使用网格或块。
> > > ![图像](https://user-images.githubusercontent.com/36197596/110413328-9fef3280-80c8-11eb-9a5e-dce5068e23ea.png)
> > 
> > 
> > 如果我想在小型CUDA计算中实施限制，基于gpu-manager，我应该做什么或应该更改哪一部分？
> 
> CUDA限制基于项目[vcuda-controller](https://github.com/tkestack/vcuda-controller)

Thank you for your answer. One more question, could you please tell me how to realize the specific load distribution to a certain physical GPU?
I want to implement GPU distribution according to my own distribution method. Could you please tell me the source code of which files I need to learn?
Thank you very much.

**Comment by mYmNeo** [comment]
> > > > 对于小型cuda计算，没有足够的空间来限制使用，但是对于训练应用程序来说。
> > > > 我看到的日志是，增量始终为0。并且没有使用网格或块。
> > > > ![图像](https://user-images.githubusercontent.com/36197596/110413328-9fef3280-80c8-11eb-9a5e-dce5068e23ea.png)
> > > 
> > > 
> > > 如果我想在小型CUDA计算中实施限制，基于gpu-manager，我应该做什么或应该更改哪一部分？
> > 
> > 
> > CUDA限制基于项目[vcuda-controller](https://github.com/tkestack/vcuda-controller)
> 
> Thank you for your answer. One more question, could you please tell me how to realize the specific load distribution to a certain physical GPU?
> I want to implement GPU distribution according to my own distribution method. Could you please tell me the source code of which files I need to learn?
> Thank you very much.

The log already showed the file name and line 😄

**Comment by ZeoSophia** [comment]
> > > > > 对于小型cuda计算，没有足够的空间来限制使用，但是对于训练应用程序来说。
> > > > > 我看到的日志是，增量始终为0。并且没有使用网格或块。
> > > > > ![图像](https://user-images.githubusercontent.com/36197596/110413328-9fef3280-80c8-11eb-9a5e-dce5068e23ea.png)
> > > > 
> > > > 
> > > > 如果我想在小型CUDA计算中实施限制，基于gpu-manager，我应该做什么或应该更改哪一部分？
> > > 
> > > 
> > > CUDA限制基于项目[vcuda-controller](https://github.com/tkestack/vcuda-controller)
> > 
> > 
> > 谢谢您的回答。还有一个问题，能否请您告诉我如何实现特定物理GPU的特定负载分配？
> > 我想根据自己的分配方法来实现GPU分配。您能告诉我我需要学习哪些文件的源代码吗？
> > 非常感谢你。
> 
> 日志已经显示了文件名和行 😄
Oh, I was very careless. Thank you very much！

**Comment by ZeoSophia** [comment]
And I found a problem ，this shows in version 1.1.4 but everything in version 1.1.2 is ok
![image](https://user-images.githubusercontent.com/36197596/112112960-26d7fb00-8bf1-11eb-87b7-b87305a842c5.png)
