### ISSUE TITLE
How to configure automatic log deletion

### ISSUE THREAD

**Issue by cutiechi** [tkestack/gpu-manager#79]
How to configure automatic log deletion？
![图片](https://user-images.githubusercontent.com/27606234/114803884-dc523480-9dd2-11eb-9bbb-2ab631b4150a.png)

**Comment by mYmNeo** [comment]
No automatic log deletion is provided, you have to run a single script to clean log

**Comment by cutiechi** [comment]
@mYmNeo Thanks
