### ISSUE TITLE
failed to get response from manager error rpc error code=Unknown desc=empty pids

### ISSUE THREAD

**Issue by zxt620** [tkestack/gpu-manager#80]
when i access the pod of gpu ,execute 'nvidia-smi ' or script to use the gpu Resourece ,it occurd this problem.hope someone to fix it .Thanks. the version of gpu-manager is 1.1.4

**Comment by mYmNeo** [comment]
https://github.com/tkestack/gpu-manager/issues/55

**Comment by zxt620** [comment]
> #55
my cgroups is not systemd. so  i problem is still here.

**Comment by mYmNeo** [comment]
> > #55
> > my cgroups is not systemd. so  i problem is still here.

Please provides your process cgroup path, both in and out of the container

**Comment by zxt620** [comment]
> > > #55
> > > my cgroups is not systemd. so  i problem is still here.
> 
> Please provides your process cgroup path, both in and out of the container

**Comment by zxt620** [comment]
> > > > #55
> > > > my cgroups is not systemd. so  i problem is still here.
> > 
> > 
> > Please provides your process cgroup path, both in and out of the container

why want to konw the cgropu path.  gpu resourece is not limited  by cgourp .不是通过拦截cuda调用做资源限制的吗

**Comment by zxt620** [comment]
> 

> > > > > #55
> > > > > my cgroups is not systemd. so  i problem is still here.
> > > 
> > > 
> > > Please provides your process cgroup path, both in and out of the container
> 
> why want to konw the cgropu path. gpu resourece is not limited by cgourp .不是通过拦截cuda调用做资源限制的吗

还有另外一个问题 就是我们容器化之后 测试之后 发现性能有所下降且下降的挺多

**Comment by iuno90qo** [comment]
> > #55
> > my cgroups is not systemd. so  i problem is still here.

hi,i met the same problem, how did you solve this?

**Comment by iuno90qo** [comment]
> > > #55
> > > my cgroups is not systemd. so  i problem is still here.
> 
> hi,i met the same problem, how did you solve this?

solve this，in gpumanger.yaml, delete the "--cgroup-driver=systemd" is ok.
