### ISSUE TITLE
"device plugin PreStartContainer rpc failed with err" on k8s 1.20

### ISSUE THREAD

**Issue by iamkulele** [tkestack/gpu-manager#81]
Hi mYmNeo,

Could you help to check this problem? When I upgrade k8s from 1.19 to 1.20, vcuda-test fail at CreateContainerConfigError.

[logs]
Warning  Failed     4s (x3 over 6s)  kubelet            Error: device plugin PreStartContainer rpc failed with err: rpc error: code = Unknown desc = PreStartContainer check failed, failed to read from checkpoint file due to json: cannot unmarshal object into Go struct field PodDevicesEntry.Data.PodDeviceEntries.DeviceIDs of type []string

**Comment by iamkulele** [comment]
refer to #62, may be the same issue.

**Comment by timozerrer** [comment]
Same issue. Any solution yet @iamkulele ?

**Comment by mYmNeo** [comment]
Cherry picked the commit to the release-1.1.0

**Comment by timozerrer** [comment]
> release-1.1.0

What do you mean? Use this release https://github.com/tkestack/gpu-manager/releases/tag/v1.1.0 for kubelet 1.20+ ?

**Comment by mYmNeo** [comment]
> > release-1.1.0
> 
> What do you mean? Use this release https://github.com/tkestack/gpu-manager/releases/tag/v1.1.0 for kubelet 1.20+ ?
> 
> Edit: This branch (https://github.com/tkestack/gpu-manager/tree/release-1.1.0) works. So latest release is broken???

Branch release-1.1.0, tag is v1.1.5
