### ISSUE TITLE
是否需要安装gpu-admission？

### ISSUE THREAD

**Issue by cailun01** [tkestack/gpu-manager#88]
我希望使用gpu-manager来限制GPU utilization，请问在安装gpu-manager之前，是否需要先安装gpu-admission？

**Comment by mYmNeo** [comment]
> 我希望使用gpu-manager来限制GPU utilization，请问在安装gpu-manager之前，是否需要先安装gpu-admission？

需要，gpu-admission 用来指导 gpu-manager 使用哪个卡

**Comment by cailun01** [comment]
> > 我希望使用gpu-manager来限制GPU utilization，请问在安装gpu-manager之前，是否需要先安装gpu-admission？
> 
> 需要，gpu-admission 用来指导 gpu-manager 使用哪个卡

感谢！
