### ISSUE TITLE
Undefined symbol error was reported when I set up gpu-manager

### ISSUE THREAD

**Issue by cooboos** [tkestack/gpu-manager#9]
Hi,  I try to set up the GPU-manager in my environment, but I found some problems. When gpu-manager was run, it will invoke nvml.Init(), which is implemented in go-nvml/wrapper.go. But most of this file was commented.
I check the source and find the new implementation in vcuda-controller, but it does not reimplement NVML_D(xxx).
Do I miss something or some mismatch in the version ?

Version:  master 

Thank you.

**Comment by cooboos** [comment]
error like this：

> `copy /usr/local/host/lib/nvidia-440/bin/nvidia-persistenced to /usr/local/nvidia/bin/
copy /usr/local/host/bin/nvidia-smi to /usr/local/nvidia/bin/
copy /usr/local/host/lib/nvidia-440/bin/nvidia-smi to /usr/local/nvidia/bin/
rebuild ldcache
launch gpu manager
E1216 06:26:30.211539  123553 server.go:132] Unable to set Type=notify in systemd service file?
/usr/bin/gpu-manager: symbol lookup error: /usr/bin/gpu-manager: undefined symbol: nvmlInit_dlib`

**Comment by KarlCyan** [comment]
You can refer to #7

**Comment by mYmNeo** [comment]
@cooboos Fixed. Please checkout the latest commit

**Comment by cooboos** [comment]
@mYmNeo  Got it. Thank you.
