### ISSUE TITLE
gpu-manager fell into CrushBackOff

### ISSUE THREAD

**Issue by Thatwho** [tkestack/gpu-manager#91]
I am trying to run gpu-manager on the server which can't connect to the world wode web, so I download the image tkestack/gpu-manager:v1.0.4.
But after I apply the daemonset, the gpu-manager pod status soon fell into Crush LoopBackOff.
Here is logs photo
![IMG_20210516_202153](https://user-images.githubusercontent.com/28083815/118396952-73d1ce00-b684-11eb-9eef-ceabf7d63567.jpg)
![IMG_20210516_202059](https://user-images.githubusercontent.com/28083815/118396956-78968200-b684-11eb-8fa1-3b2585cce987.jpg)
![IMG_20210516_202043](https://user-images.githubusercontent.com/28083815/118396958-7a604580-b684-11eb-952a-57a445312e0a.jpg)

So, I have no idea what cause this problem. Is there any  solution? Thank you!

**Comment by mYmNeo** [comment]
The old one had a timeout check that will cause the gpu-manager exit. Try to use a latest version.

**Comment by Thatwho** [comment]
> The old one had a timeout check that will cause the gpu-manager exit. Try to use a latest version.

THX! that really help! But it seems got another error:
![IMG_20210517_170750](https://user-images.githubusercontent.com/28083815/118463760-b8b43e00-b732-11eb-8b88-a0f158d234e2.jpg)
![IMG_20210517_170643](https://user-images.githubusercontent.com/28083815/118463770-bce05b80-b732-11eb-8bb2-7c0e7552d924.jpg)

**Comment by Thatwho** [comment]
> The old one had a timeout check that will cause the gpu-manager exit. Try to use a latest version.

I'v changed it into v1.0.9, It works! That's really help! Thanks!
