### ISSUE TITLE
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1

### ISSUE THREAD

**Issue by jiangxiaobin96** [tkestack/gpu-manager#92]
make过程问题描述
```
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-622208971/000012.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

make: *** [all] Error 1
```
这个问题是gcc版本太旧了吗

**Comment by mYmNeo** [comment]
> make过程问题描述
> 
> ```
> /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
> /usr/bin/ld: /tmp/go-link-622208971/000012.o: unrecognized relocation (0x2a) in section `.text'
> /usr/bin/ld: final link failed: Bad value
> collect2: error: ld returned 1 exit status
> 
> make: *** [all] Error 1
> ```
> 
> 这个问题是gcc版本太旧了吗

这个不太了解，你只在 linux 下编译的吗？

**Comment by jiangxiaobin96** [comment]
tlinux上编译的，

**Comment by mYmNeo** [comment]
这是你 ld 版本的问题

**Comment by jiangxiaobin96** [comment]
升级ld还是得升级gcc，请问，这个有gcc版本要求吗，最低多少

**Comment by jiangxiaobin96** [comment]
我问题解决了，是ld版本太低了
