### ISSUE TITLE
gpu-admission是否应该安装在Master节点上？

### ISSUE THREAD

**Issue by cailun01** [tkestack/gpu-manager#93]
我试图用gpu-manager来限制GPU utilization，需要安装gpu-admission。我的master节点没有GPU，node1节点有GPU。请问应该把gpu-admission安装在master节点上还是node1节点上？

**Comment by mYmNeo** [comment]
> 我试图用gpu-manager来限制GPU utilization，需要安装gpu-admission。我的master节点没有GPU，node1节点有GPU。请问应该把gpu-admission安装在master节点上还是node1节点上？

master节点，gpu-admission 不需要 gpu 运行

**Comment by cailun01** [comment]
> > 我试图用gpu-manager来限制GPU utilization，需要安装gpu-admission。我的master节点没有GPU，node1节点有GPU。请问应该把gpu-admission安装在master节点上还是node1节点上？
> 
> master节点，gpu-admission 不需要 gpu 运行

谢谢！
