### ISSUE TITLE
failed to read from checkpoint

### ISSUE THREAD

**Issue by Thatwho** [tkestack/gpu-manager#94]
HI, I'm using image of gpu-manager v1.0.9. After apply the yaml, It seems fine. But the pod which set vcuda-core and vcuda-memeory can't runing.
I had test with 'menghe.tencentcloudcr.com/public/tensorflow-gputest:0.2', and it had sucked
![IMG_20210518_100913](https://user-images.githubusercontent.com/28083815/118579696-24dd8300-b7c1-11eb-8f80-0bbfc107bce6.jpg)

and i'd got this log from gpu-manager
![IMG_20210518_095858](https://user-images.githubusercontent.com/28083815/118579733-34f56280-b7c1-11eb-941e-69c2aa7bb1ea.jpg)

Is there something wrong in my server? Thank you!

**Comment by Thatwho** [comment]
oh，it seems that I didn't update deploy file after updating image version. Sorry!

**Comment by SinghDivneet** [comment]
What version of the `nvidia/k8s-device-plugin` are you using?
