### ISSUE TITLE
Support for k8's cluster 1.19+ 

### ISSUE THREAD

**Issue by SinghDivneet** [tkestack/gpu-manager#98]
With the runtime transition from docker to container, the GPU manager plugin doesn't seem to launch the container interface 

using the latest image: v1.14 on docker hub 

The exact error message I get the daemonset container logs 

`rebuild ldcache
launch gpu manager
E0529 19:01:01.516570   24467 server.go:131] Unable to set Type=notify in systemd service file?
E0529 19:01:06.518410   24467 server.go:152] can't create container runtime manager: context deadline exceeded`

**Comment by mYmNeo** [comment]
See #94
